const logsList = {
    "total": 122,
    "rows": [{
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": null,
            "createTime": null,
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "operId": 2404,
            "title": "来料检验单",
            "businessType": 1,
            "businessTypes": null,
            "method": "com.qcp.iqc.controller.IncomingInspectionController.addSave()",
            "operatorType": 1,
            "operName": "admin",
            "deptName": "上海益吉",
            "operUrl": "/sqm-admin/iqc/incomingInspection/add",
            "operIp": "42.48.78.143",
            "operLocation": "XX XX",
            "operParam": "{\r\n  \"purchaseNo\" : [ \"CGD-1028-001\" ],\r\n  \"purchaseId\" : [ \"c7476329f97111e98b0300163e1ae183\" ],\r\n  \"purchaseDetailId\" : [ \"c74ac68bf97111e98b0300163e1ae183\" ],\r\n  \"code\" : [ \"erp-zhuanzh-1028-02\" ],\r\n  \"supplierNo\" : [ \"C2025\" ],\r\n  \"supplierId\" : [ \"038820aff95511e98b0300163e1ae183\" ],\r\n  \"supplierName\" : [ \"上海艺嘉金属制品有限公司\" ],\r\n  \"partName\" : [ \"转轴\" ],\r\n  \"partId\" : [ \"d0be3d97f97011e98b0300163e1ae183\" ],\r\n  \"materials\" : [ \"不锈钢、铜\" ],\r\n  \"specification\" : [ \"GG-10*28-01\" ],\r\n  \"standardId\" : [ \"4f118dcef97111e98b0300163e1ae183\" ],\r\n  \"batchNo\" : [ \"rrrrr\" ],\r\n  \"incomingNum\" : [ \"220\" ],\r\n  \"inspectNum\" : [ \"20\" ]\r\n}",
            "status": 0,
            "errorMsg": null,
            "operTime": "2020-10-18 07:31:27"
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": null,
            "createTime": null,
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "operId": 2403,
            "title": "审核计划",
            "businessType": 1,
            "businessTypes": null,
            "method": "com.qcp.sysman.controller.AuditPlanController.addSave()",
            "operatorType": 1,
            "operName": "15502169523",
            "deptName": "上海益吉",
            "operUrl": "/sqm-admin/sysman/auditPlan/add",
            "operIp": "49.78.18.252",
            "operLocation": "XX XX",
            "operParam": "{\r\n  \"planId\" : [ \"\" ],\r\n  \"supplierId\" : [ \"02c832caf95511e98b0300163e1ae183\" ],\r\n  \"supplier.supplierNo\" : [ \"C1001\" ],\r\n  \"supplier.supplierName\" : [ \"太仓市汇湖电镀有限公司B-1车间\" ],\r\n  \"reviewCategory\" : [ \"1\" ],\r\n  \"quaCategory\" : [ \"1\" ],\r\n  \"quaName\" : [ \"0\" ],\r\n  \"cerValidityStart\" : [ \"2020-08-22\" ],\r\n  \"cerValidityEnd\" : [ \"2020-08-29\" ],\r\n  \"linkmanName\" : [ \"ss\" ],\r\n  \"email\" : [ \"ss\" ],\r\n  \"address\" : [ \"ssss\" ],\r\n  \"mainProducts\" : [ \"sss\" ],\r\n  \"reviewWay\" : [ \"0\" ],\r\n  \"projectApprUserId\" : [ \"0960c182369111ea8b0300163e1ae183\" ],\r\n  \"projectApprUserName\" : [ \"许文平\" ],\r\n  \"resultApprUserId\" : [ \"0963f3da369111ea8b0300163e1ae183\" ],\r\n  \"resultApprUserName\" : [ \"黄子重\" ]\r\n}",
            "status": 0,
            "errorMsg": null,
            "operTime": "2020-08-22 11:56:00"
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": null,
            "createTime": null,
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "operId": 2402,
            "title": "来料检验单",
            "businessType": 2,
            "businessTypes": null,
            "method": "com.qcp.iqc.controller.IncomingInspectionController.editSave()",
            "operatorType": 1,
            "operName": "15502169523",
            "deptName": "上海益吉",
            "operUrl": "/sqm-admin/iqc/incomingInspection/edit",
            "operIp": "223.166.82.137",
            "operLocation": "XX XX",
            "operParam": "{\r\n  \"resultValue10\" : [ \"\" ],\r\n  \"resultValue20\" : [ \"\" ],\r\n  \"resultValue30\" : [ \"\" ],\r\n  \"resultValue40\" : [ \"\" ],\r\n  \"resultValue50\" : [ \"\" ],\r\n  \"resultValue11\" : [ \"\" ],\r\n  \"resultValue21\" : [ \"\" ],\r\n  \"resultValue31\" : [ \"\" ],\r\n  \"resultValue41\" : [ \"\" ],\r\n  \"resultValue51\" : [ \"\" ],\r\n  \"resultValue12\" : [ \"\" ],\r\n  \"resultValue22\" : [ \"\" ],\r\n  \"resultValue32\" : [ \"\" ],\r\n  \"resultValue42\" : [ \"\" ],\r\n  \"resultValue52\" : [ \"\" ],\r\n  \"purchaseId\" : [ \"c7476329f97111e98b0300163e1ae183\" ],\r\n  \"inspectionId\" : [ \"b2633188d56311ea9c0b00163e1ae183\" ],\r\n  \"inspectionNo\" : [ \"IQC-20200803-0001\" ],\r\n  \"determine\" : [ \"0\" ],\r\n  \"environmental\" : [ \"0\" ],\r\n  \"environmentalProtectionLabel\" : [ \"0\" ],\r\n  \"rejectRatio\" : [ \"2.38\" ],\r\n  \"inspectUserName\" : [ \"王海森\" ],\r\n  \"inspectUserId\" : [ \"2c93b4f1676ebbe0016771ef50b6001d\" ],\r\n  \"storeUserName\" : [ \"\" ],\r\n  \"storeUserId\" : [ \"\" ],\r\n  \"materialApproval\" : [ \"\" ],\r\n  \"qualityApproval\" : [ \"\" ],\r\n  \"remark\" : [ \"\" ],\r\n  \"list\" : [ \"[{\\\"companyId\\\":\\\"402880e762656861016266cc46140049\\\",\\\"companyName\\\":null,\\\"searchValue\\\":null,\\\"createBy\\\":null,\\\"createTime\\\":null,\\\"updateBy\\\":null,\\\"updateTime\\\":null,\\\"createUserName\\\":\\\"15502169523\\\",\\\"updateUserName\\\":null,\\\"remark\\\":null,\\\"deleteFlag\\\":\\\"0\\\",\\\"createUserId\\\":\\\"2c93b4f1676ebbe0016771ef50b6001d\\\",\\\"createDate\\\":\\\"2020-08-03 08:31:17\\\",\\\"updateUserId\\\":null,\\\"updateDate\\\":null,\\\"params\\\":{},\\\"detailId\\\":\\\"b266d509d56311ea9c0b00163e1ae183\\\",\\\"inspectionId\\\":\\\"b2633188d56311ea9c0b00163e1ae183\\\",\\\"standardId\\\":\\\"4f118dcef97111e98b0300163e1ae183\\\",\\\"inspectionItem\\\":\\\"转轴长\\\",\\\"inspectionType\\\":\\\"长\\\",\\\"tolerances\\\":\\\"1.5mm\\\",\\\"determine\\\":\\\"1\\\",\\\"picture\\\":\\\"20200803163210.png\\\",\\\"resultList\\\":[{\\\"companyId\\\":\\\"402880e762656861016266cc46140049\\\",\\\"companyName\\\":null,\\\"searchValue\\\":null,\\\"createBy\\\":null,\\\"createTime\\\":null,\\\"updateBy\\\":null,\\\"updateTime\\\":null,\\\"createUserName\\\":\\\"15502169523\\\",\\\"updateUserName\\\":null,\\\"remark\\\":null,\\\"deleteFlag\\\":\\\"0\\\",\\\"createUserId\\\":\\\"2c93b4f1676e",
            "status": 0,
            "errorMsg": null,
            "operTime": "2020-08-03 16:32:23"
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": null,
            "createTime": null,
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "operId": 2401,
            "title": "来料检验单",
            "businessType": 1,
            "businessTypes": null,
            "method": "com.qcp.iqc.controller.IncomingInspectionController.addSave()",
            "operatorType": 1,
            "operName": "15502169523",
            "deptName": "上海益吉",
            "operUrl": "/sqm-admin/iqc/incomingInspection/add",
            "operIp": "223.166.82.137",
            "operLocation": "XX XX",
            "operParam": "{\r\n  \"purchaseNo\" : [ \"CGD-1028-001\" ],\r\n  \"purchaseId\" : [ \"c7476329f97111e98b0300163e1ae183\" ],\r\n  \"purchaseDetailId\" : [ \"c7492578f97111e98b0300163e1ae183\" ],\r\n  \"code\" : [ \"erp-zhuanzh-1028-01\" ],\r\n  \"supplierNo\" : [ \"C2025\" ],\r\n  \"supplierId\" : [ \"038820aff95511e98b0300163e1ae183\" ],\r\n  \"supplierName\" : [ \"上海艺嘉金属制品有限公司\" ],\r\n  \"partName\" : [ \"转轴\" ],\r\n  \"partId\" : [ \"d0be3d97f97011e98b0300163e1ae183\" ],\r\n  \"materials\" : [ \"不锈钢、铜\" ],\r\n  \"specification\" : [ \"GG-10*28-01\" ],\r\n  \"standardId\" : [ \"4f118dcef97111e98b0300163e1ae183\" ],\r\n  \"batchNo\" : [ \"001\" ],\r\n  \"incomingNum\" : [ \"210\" ],\r\n  \"inspectNum\" : [ \"5\" ]\r\n}",
            "status": 0,
            "errorMsg": null,
            "operTime": "2020-08-03 16:31:17"
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": null,
            "createTime": null,
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "operId": 2400,
            "title": "来料检验单",
            "businessType": 5,
            "businessTypes": null,
            "method": "com.qcp.iqc.controller.IncomingInspectionController.export()",
            "operatorType": 1,
            "operName": "admin",
            "deptName": "上海益吉",
            "operUrl": "/sqm-admin/iqc/incomingInspection/export",
            "operIp": "223.166.82.137",
            "operLocation": "XX XX",
            "operParam": "{\r\n  \"inspectionNo\" : [ \"\" ],\r\n  \"purchaseNo\" : [ \"\" ],\r\n  \"batchNo\" : [ \"\" ],\r\n  \"determine\" : [ \"\" ],\r\n  \"environmental\" : [ \"\" ],\r\n  \"state\" : [ \"\" ]\r\n}",
            "status": 0,
            "errorMsg": null,
            "operTime": "2020-07-31 16:25:03"
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": null,
            "createTime": null,
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "operId": 2399,
            "title": "文件任务",
            "businessType": 2,
            "businessTypes": null,
            "method": "com.qcp.filetask.controller.FileTaskController.uploadFilesSave()",
            "operatorType": 1,
            "operName": "admin",
            "deptName": "上海益吉",
            "operUrl": "/sqm-admin/filetask/fileTask/uploadFiles",
            "operIp": "223.166.81.134",
            "operLocation": "XX XX",
            "operParam": "{\r\n  \"taskId\" : [ \"12f1f1ccc4e911ea9c0b00163e1ae183\" ]\r\n}",
            "status": 0,
            "errorMsg": null,
            "operTime": "2020-07-13 17:13:53"
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": null,
            "createTime": null,
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "operId": 2398,
            "title": "文件任务",
            "businessType": 1,
            "businessTypes": null,
            "method": "com.qcp.filetask.controller.FileTaskController.addSave()",
            "operatorType": 1,
            "operName": "admin",
            "deptName": "上海益吉",
            "operUrl": "/sqm-admin/filetask/fileTask/add",
            "operIp": "223.166.81.134",
            "operLocation": "XX XX",
            "operParam": "{\r\n  \"taskId\" : [ \"\" ],\r\n  \"taskNo\" : [ \"\" ],\r\n  \"fileType\" : [ \"3\" ],\r\n  \"supplierId\" : [ \"02c832caf95511e98b0300163e1ae183\" ],\r\n  \"supplier.supplierNo\" : [ \"C1001\" ],\r\n  \"supplier.supplierName\" : [ \"太仓市汇湖电镀有限公司B-1车间\" ],\r\n  \"compStartDate\" : [ \"2020-07-12\" ],\r\n  \"compEndDate\" : [ \"2020-08-19\" ],\r\n  \"compPeoId\" : [ \"admin\" ],\r\n  \"compPeoName\" : [ \"admin\" ],\r\n  \"approverId\" : [ \"2c93b4f16bb1e070016bd5752f110397\" ],\r\n  \"approverName\" : [ \"徐丽霞\" ],\r\n  \"dayNum\" : [ \"10\" ]\r\n}",
            "status": 0,
            "errorMsg": null,
            "operTime": "2020-07-13 17:13:12"
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": null,
            "createTime": null,
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "operId": 2397,
            "title": "来料检验单",
            "businessType": 2,
            "businessTypes": null,
            "method": "com.qcp.iqc.controller.IncomingInspectionController.editSave()",
            "operatorType": 1,
            "operName": "admin",
            "deptName": "上海益吉",
            "operUrl": "/sqm-admin/iqc/incomingInspection/edit",
            "operIp": "223.166.81.134",
            "operLocation": "XX XX",
            "operParam": "{\r\n  \"resultValue10\" : [ \"8\" ],\r\n  \"resultValue20\" : [ \"8\" ],\r\n  \"resultValue30\" : [ \"7\" ],\r\n  \"resultValue11\" : [ \"5\" ],\r\n  \"resultValue21\" : [ \"6\" ],\r\n  \"resultValue31\" : [ \"8\" ],\r\n  \"purchaseId\" : [ \"a9b1b40ac4de11ea9c0b00163e1ae183\" ],\r\n  \"inspectionId\" : [ \"2f19708bc4e811ea9c0b00163e1ae183\" ],\r\n  \"inspectionNo\" : [ \"IQC-20200713-0002\" ],\r\n  \"determine\" : [ \"0\" ],\r\n  \"environmental\" : [ \"0\" ],\r\n  \"environmentalProtectionLabel\" : [ \"0\" ],\r\n  \"rejectRatio\" : [ \"0.00\" ],\r\n  \"inspectUserName\" : [ \"admin\" ],\r\n  \"inspectUserId\" : [ \"admin\" ],\r\n  \"storeUserName\" : [ \"杨彪\" ],\r\n  \"storeUserId\" : [ \"2c93b4f16774ac33016776e5fa72000d\" ],\r\n  \"materialApproval\" : [ \"王海森\" ],\r\n  \"qualityApproval\" : [ \"徐丽霞\" ],\r\n  \"state\" : [ \"1\" ],\r\n  \"remark\" : [ \"此次来料500，抽检3个，全部合格\" ],\r\n  \"list\" : [ \"[{\\\"companyId\\\":\\\"402880e762656861016266cc46140049\\\",\\\"companyName\\\":null,\\\"searchValue\\\":null,\\\"createBy\\\":null,\\\"createTime\\\":null,\\\"updateBy\\\":null,\\\"updateTime\\\":null,\\\"createUserName\\\":\\\"admin\\\",\\\"updateUserName\\\":null,\\\"remark\\\":null,\\\"deleteFlag\\\":\\\"0\\\",\\\"createUserId\\\":\\\"admin\\\",\\\"createDate\\\":\\\"2020-07-13 09:06:50\\\",\\\"updateUserId\\\":null,\\\"updateDate\\\":null,\\\"params\\\":{},\\\"detailId\\\":\\\"2f1cd4ccc4e811ea9c0b00163e1ae183\\\",\\\"inspectionId\\\":\\\"2f19708bc4e811ea9c0b00163e1ae183\\\",\\\"standardId\\\":\\\"7b06c000c4dd11ea9c0b00163e1ae183\\\",\\\"inspectionItem\\\":\\\"宝来滤清器\\\",\\\"inspectionType\\\":\\\"直径\\\",\\\"tolerances\\\":\\\"<10mm\\\",\\\"determine\\\":\\\"0\\\",\\\"picture\\\":null,\\\"resultList\\\":[{\\\"companyId\\\":\\\"402880e762656861016266cc46140049\\\",\\\"companyName\\\":null,\\\"searchValue\\\":null,\\\"createBy\\\":null,\\\"createTime\\\":null,\\\"updateBy\\\":null,\\\"updateTime\\\":null,\\\"createUserName\\\":\\\"admin\\\",\\\"updateUserName\\\":null,\\\"remark\\\":null,\\\"deleteFlag\\\":\\\"0\\\",\\\"createUserId\\\":\\\"admin\\\",\\\"createDate\\\":\\\"2020-07-13 09:06:50\\\",\\\"updateUserId\\\":null,\\\"updateDate\\\":null,\\\"params\\\":{},\\\"resultId\\\":\\\"2f1e07f7c4e811ea9c0b00163e1ae183\\\",\\\"detailId\\\":\\\"2f1cd4ccc4e811ea9c0b00163e1ae183\\\",\\\"resultValue\\\":\\\"8\\\",\\\"enteringUserId\\\":\\\"admin\\\",\\\"enteringUse",
            "status": 0,
            "errorMsg": null,
            "operTime": "2020-07-13 17:10:14"
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": null,
            "createTime": null,
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "operId": 2396,
            "title": "来料检验单",
            "businessType": 1,
            "businessTypes": null,
            "method": "com.qcp.iqc.controller.IncomingInspectionController.addSave()",
            "operatorType": 1,
            "operName": "admin",
            "deptName": "上海益吉",
            "operUrl": "/sqm-admin/iqc/incomingInspection/add",
            "operIp": "223.166.81.134",
            "operLocation": "XX XX",
            "operParam": "{\r\n  \"purchaseNo\" : [ \"CGD20200713\" ],\r\n  \"purchaseId\" : [ \"a9b1b40ac4de11ea9c0b00163e1ae183\" ],\r\n  \"purchaseDetailId\" : [ \"a9b4399fc4de11ea9c0b00163e1ae183\" ],\r\n  \"code\" : [ \"ERP-071301\" ],\r\n  \"supplierNo\" : [ \"C1002\" ],\r\n  \"supplierId\" : [ \"02cd6e9df95511e98b0300163e1ae183\" ],\r\n  \"supplierName\" : [ \"上海达克罗涂复工业有限公司\" ],\r\n  \"partName\" : [ \"滤清器\" ],\r\n  \"partId\" : [ \"9cf23272c4db11ea9c0b00163e1ae183\" ],\r\n  \"materials\" : [ \"不锈钢、铜、钛、活性炭、高聚物\" ],\r\n  \"specification\" : [ \"210*270\" ],\r\n  \"standardId\" : [ \"7b06c000c4dd11ea9c0b00163e1ae183\" ],\r\n  \"batchNo\" : [ \"P2020-0713-2/2\" ],\r\n  \"incomingNum\" : [ \"500\" ],\r\n  \"inspectNum\" : [ \"3\" ]\r\n}",
            "status": 0,
            "errorMsg": null,
            "operTime": "2020-07-13 17:07:20"
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": null,
            "createTime": null,
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "operId": 2395,
            "title": "投诉单",
            "businessType": 10,
            "businessTypes": null,
            "method": "com.qcp.filetask.controller.FileTaskController.approveSave()",
            "operatorType": 1,
            "operName": "admin",
            "deptName": "上海益吉",
            "operUrl": "/sqm-admin/filetask/fileTask/approveSave",
            "operIp": "223.166.81.134",
            "operLocation": "XX XX",
            "operParam": "{\r\n  \"approvalState\" : [ \"0\" ],\r\n  \"approvalAdvice\" : [ \"通过\" ],\r\n  \"dataId\" : [ \"62f25739c4e611ea9c0b00163e1ae183\" ],\r\n  \"dataFlag\" : [ \"fileTask.appro\" ]\r\n}",
            "status": 0,
            "errorMsg": null,
            "operTime": "2020-07-13 16:59:26"
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": null,
            "createTime": null,
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "operId": 2394,
            "title": "文件任务",
            "businessType": 2,
            "businessTypes": null,
            "method": "com.qcp.filetask.controller.FileTaskController.uploadFilesSave()",
            "operatorType": 1,
            "operName": "admin",
            "deptName": "上海益吉",
            "operUrl": "/sqm-admin/filetask/fileTask/uploadFiles",
            "operIp": "223.166.81.134",
            "operLocation": "XX XX",
            "operParam": "{\r\n  \"taskId\" : [ \"62f25739c4e611ea9c0b00163e1ae183\" ]\r\n}",
            "status": 0,
            "errorMsg": null,
            "operTime": "2020-07-13 16:58:09"
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": null,
            "createTime": null,
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "operId": 2393,
            "title": "文件任务",
            "businessType": 2,
            "businessTypes": null,
            "method": "com.qcp.filetask.controller.FileTaskController.editSave()",
            "operatorType": 1,
            "operName": "admin",
            "deptName": "上海益吉",
            "operUrl": "/sqm-admin/filetask/fileTask/edit",
            "operIp": "223.166.81.134",
            "operLocation": "XX XX",
            "operParam": "{\r\n  \"taskId\" : [ \"62f25739c4e611ea9c0b00163e1ae183\" ],\r\n  \"taskNo\" : [ \"FT-2020070005\" ],\r\n  \"fileType\" : [ \"2\" ],\r\n  \"supplierId\" : [ \"02cd6e9df95511e98b0300163e1ae183\" ],\r\n  \"supplier.supplierNo\" : [ \"C1002\" ],\r\n  \"supplier.supplierName\" : [ \"上海达克罗涂复工业有限公司\" ],\r\n  \"compStartDate\" : [ \"2020-07-12\" ],\r\n  \"compEndDate\" : [ \"2020-07-15\" ],\r\n  \"compPeoId\" : [ \"admin\" ],\r\n  \"compPeoName\" : [ \"admin\" ],\r\n  \"approverId\" : [ \"2c93b4f16bb1e070016bd5752f110397\" ],\r\n  \"approverName\" : [ \"徐丽霞\" ],\r\n  \"dayNum\" : [ \"10\" ]\r\n}",
            "status": 0,
            "errorMsg": null,
            "operTime": "2020-07-13 16:56:55"
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": null,
            "createTime": null,
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "operId": 2392,
            "title": "文件任务",
            "businessType": 2,
            "businessTypes": null,
            "method": "com.qcp.filetask.controller.FileTaskController.editSave()",
            "operatorType": 1,
            "operName": "admin",
            "deptName": "上海益吉",
            "operUrl": "/sqm-admin/filetask/fileTask/edit",
            "operIp": "223.166.81.134",
            "operLocation": "XX XX",
            "operParam": "{\r\n  \"taskId\" : [ \"62f25739c4e611ea9c0b00163e1ae183\" ],\r\n  \"taskNo\" : [ \"FT-2020070005\" ],\r\n  \"fileType\" : [ \"2\" ],\r\n  \"supplierId\" : [ \"02cd6e9df95511e98b0300163e1ae183\" ],\r\n  \"supplier.supplierNo\" : [ \"C1002\" ],\r\n  \"supplier.supplierName\" : [ \"上海达克罗涂复工业有限公司\" ],\r\n  \"compStartDate\" : [ \"2020-07-12\" ],\r\n  \"compEndDate\" : [ \"2020-07-15\" ],\r\n  \"compPeoId\" : [ \"2c93b4f16bb1e070016bd5752f110397\" ],\r\n  \"compPeoName\" : [ \"徐丽霞\" ],\r\n  \"approverId\" : [ \"2c93b4f16bb1e070016bd5752f110397\" ],\r\n  \"approverName\" : [ \"徐丽霞\" ],\r\n  \"dayNum\" : [ \"10\" ]\r\n}",
            "status": 0,
            "errorMsg": null,
            "operTime": "2020-07-13 16:56:45"
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": null,
            "createTime": null,
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "operId": 2391,
            "title": "年度计划",
            "businessType": 10,
            "businessTypes": null,
            "method": "com.qcp.sysman.controller.AuditPlanController.projectApprSave()",
            "operatorType": 1,
            "operName": "admin",
            "deptName": "上海益吉",
            "operUrl": "/sqm-admin/sysman/auditPlan/projectApprSave",
            "operIp": "223.166.81.134",
            "operLocation": "XX XX",
            "operParam": "{\r\n  \"approvalState\" : [ \"0\" ],\r\n  \"approvalAdvice\" : [ \"加上车间5S填报情况\" ],\r\n  \"dataId\" : [ \"1482c3aec4e611ea9c0b00163e1ae183\" ],\r\n  \"dataFlag\" : [ \"auditPlan.projectAppr\" ]\r\n}",
            "status": 0,
            "errorMsg": null,
            "operTime": "2020-07-13 16:55:42"
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": null,
            "createTime": null,
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "operId": 2390,
            "title": "文件任务",
            "businessType": 1,
            "businessTypes": null,
            "method": "com.qcp.filetask.controller.FileTaskController.addSave()",
            "operatorType": 1,
            "operName": "admin",
            "deptName": "上海益吉",
            "operUrl": "/sqm-admin/filetask/fileTask/add",
            "operIp": "223.166.81.134",
            "operLocation": "XX XX",
            "operParam": "{\r\n  \"taskId\" : [ \"\" ],\r\n  \"taskNo\" : [ \"\" ],\r\n  \"fileType\" : [ \"2\" ],\r\n  \"supplierId\" : [ \"02cd6e9df95511e98b0300163e1ae183\" ],\r\n  \"supplier.supplierNo\" : [ \"C1002\" ],\r\n  \"supplier.supplierName\" : [ \"上海达克罗涂复工业有限公司\" ],\r\n  \"compStartDate\" : [ \"2020-07-12\" ],\r\n  \"compEndDate\" : [ \"2020-07-20\" ],\r\n  \"compPeoId\" : [ \"2c93b4f16bb1e070016bd5752f110397\" ],\r\n  \"compPeoName\" : [ \"徐丽霞\" ],\r\n  \"approverId\" : [ \"2c93b4f16bb1e070016bd5752f110397\" ],\r\n  \"approverName\" : [ \"徐丽霞\" ],\r\n  \"dayNum\" : [ \"10\" ]\r\n}",
            "status": 0,
            "errorMsg": null,
            "operTime": "2020-07-13 16:54:28"
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": null,
            "createTime": null,
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "operId": 2389,
            "title": "审核计划",
            "businessType": 3,
            "businessTypes": null,
            "method": "com.qcp.sysman.controller.AuditPlanController.remove()",
            "operatorType": 1,
            "operName": "admin",
            "deptName": "上海益吉",
            "operUrl": "/sqm-admin/sysman/auditPlan/remove",
            "operIp": "223.166.81.134",
            "operLocation": "XX XX",
            "operParam": "{\r\n  \"ids\" : [ \"1482c3aec4e611ea9c0b00163e1ae183\" ]\r\n}",
            "status": 0,
            "errorMsg": null,
            "operTime": "2020-07-13 16:52:55"
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": null,
            "createTime": null,
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "operId": 2388,
            "title": "年度计划",
            "businessType": 10,
            "businessTypes": null,
            "method": "com.qcp.sysman.controller.AuditPlanController.resultApprSave()",
            "operatorType": 1,
            "operName": "admin",
            "deptName": "上海益吉",
            "operUrl": "/sqm-admin/sysman/auditPlan/resultApprSave",
            "operIp": "223.166.81.134",
            "operLocation": "XX XX",
            "operParam": "{\r\n  \"approvalState\" : [ \"0\" ],\r\n  \"approvalAdvice\" : [ \"通过\" ],\r\n  \"dataId\" : [ \"45073e97c4e411ea9c0b00163e1ae183\" ],\r\n  \"dataFlag\" : [ \"auditPlan.resultAppr\" ]\r\n}",
            "status": 0,
            "errorMsg": null,
            "operTime": "2020-07-13 16:51:46"
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": null,
            "createTime": null,
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "operId": 2387,
            "title": "年度计划",
            "businessType": 2,
            "businessTypes": null,
            "method": "com.qcp.sysman.controller.AuditPlanController.resultInputSave()",
            "operatorType": 1,
            "operName": "admin",
            "deptName": "上海益吉",
            "operUrl": "/sqm-admin/sysman/auditPlan/resultInputSave",
            "operIp": "223.166.81.134",
            "operLocation": "XX XX",
            "operParam": "{\r\n  \"planId\" : [ \"45073e97c4e411ea9c0b00163e1ae183\" ],\r\n  \"auditResult\" : [ \"80\" ],\r\n  \"auditFinishDate\" : [ \"2020-07-13\" ],\r\n  \"nextAuditDate\" : [ \"2021-07-13\" ],\r\n  \"reformFinishDate\" : [ \"2020-10-13\" ],\r\n  \"inconNum\" : [ \"1\" ],\r\n  \"actualAdvice\" : [ \"各方面均达到规定要求，只是车间5S表员工未及时填写\" ]\r\n}",
            "status": 0,
            "errorMsg": null,
            "operTime": "2020-07-13 16:50:12"
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": null,
            "createTime": null,
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "operId": 2386,
            "title": "年度计划",
            "businessType": 10,
            "businessTypes": null,
            "method": "com.qcp.sysman.controller.AuditPlanController.projectApprSave()",
            "operatorType": 1,
            "operName": "admin",
            "deptName": "上海益吉",
            "operUrl": "/sqm-admin/sysman/auditPlan/projectApprSave",
            "operIp": "223.166.81.134",
            "operLocation": "XX XX",
            "operParam": "{\r\n  \"approvalState\" : [ \"0\" ],\r\n  \"approvalAdvice\" : [ \"通过\" ],\r\n  \"dataId\" : [ \"45073e97c4e411ea9c0b00163e1ae183\" ],\r\n  \"dataFlag\" : [ \"auditPlan.projectAppr\" ]\r\n}",
            "status": 0,
            "errorMsg": null,
            "operTime": "2020-07-13 16:40:49"
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": null,
            "createTime": null,
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "operId": 2385,
            "title": "审核计划",
            "businessType": 1,
            "businessTypes": null,
            "method": "com.qcp.sysman.controller.AuditPlanController.addSave()",
            "operatorType": 1,
            "operName": "admin",
            "deptName": "上海益吉",
            "operUrl": "/sqm-admin/sysman/auditPlan/add",
            "operIp": "223.166.81.134",
            "operLocation": "XX XX",
            "operParam": "{\r\n  \"planId\" : [ \"\" ],\r\n  \"supplierId\" : [ \"02cd6e9df95511e98b0300163e1ae183\" ],\r\n  \"supplier.supplierNo\" : [ \"C1002\" ],\r\n  \"supplier.supplierName\" : [ \"上海达克罗涂复工业有限公司\" ],\r\n  \"reviewCategory\" : [ \"0\" ],\r\n  \"quaCategory\" : [ \"0\" ],\r\n  \"quaName\" : [ \"0\" ],\r\n  \"cerValidityStart\" : [ \"2019-06-06\" ],\r\n  \"cerValidityEnd\" : [ \"2023-07-31\" ],\r\n  \"linkmanName\" : [ \"宋勉\" ],\r\n  \"email\" : [ \"2537542901@qq.com\" ],\r\n  \"address\" : [ \"上海市嘉定区安亭镇昌吉东路1011号\" ],\r\n  \"mainProducts\" : [ \"滤清器\" ],\r\n  \"reviewWay\" : [ \"0\" ],\r\n  \"projectApprUserId\" : [ \"2c93b4f16bb1e070016bd5752f110397\" ],\r\n  \"projectApprUserName\" : [ \"徐丽霞\" ],\r\n  \"resultApprUserId\" : [ \"2c93b4f16bb1e070016bd5752f110397\" ],\r\n  \"resultApprUserName\" : [ \"徐丽霞\" ]\r\n}",
            "status": 0,
            "errorMsg": null,
            "operTime": "2020-07-13 16:38:49"
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": null,
            "createTime": null,
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "operId": 2384,
            "title": "投诉单",
            "businessType": 10,
            "businessTypes": null,
            "method": "com.qcp.complain.controller.ComplaintInvoiceController.approveSave()",
            "operatorType": 1,
            "operName": "admin",
            "deptName": "上海益吉",
            "operUrl": "/sqm-admin/complain/complaintInvoice/approveSave",
            "operIp": "223.166.81.134",
            "operLocation": "XX XX",
            "operParam": "{\r\n  \"approvalState\" : [ \"0\" ],\r\n  \"approvalAdvice\" : [ \"通过\" ],\r\n  \"dataId\" : [ \"4ae62b6ec4e311ea9c0b00163e1ae183\" ],\r\n  \"dataFlag\" : [ \"invoice.appro\" ]\r\n}",
            "status": 0,
            "errorMsg": null,
            "operTime": "2020-07-13 16:35:09"
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": null,
            "createTime": null,
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "operId": 2383,
            "title": "投诉单",
            "businessType": 2,
            "businessTypes": null,
            "method": "com.qcp.complain.controller.ComplaintInvoiceController.submitAuditSave()",
            "operatorType": 1,
            "operName": "admin",
            "deptName": "上海益吉",
            "operUrl": "/sqm-admin/complain/complaintInvoice/submitAudit",
            "operIp": "223.166.81.134",
            "operLocation": "XX XX",
            "operParam": "{\r\n  \"invoiceId\" : [ \"4ae62b6ec4e311ea9c0b00163e1ae183\" ],\r\n  \"provisionalMeasures\" : [ \"对应的几台生产仪器已停产，调试员正进行调试\" ],\r\n  \"pUserId\" : [ \"2c93b4f1676ebbe0016771ef50b6001d\" ],\r\n  \"pUserName\" : [ \"王海森\" ],\r\n  \"pDate\" : [ \"2020-07-13\" ],\r\n  \"primaryCause\" : [ \"生产仪器老化\" ],\r\n  \"cUserId\" : [ \"2c93b4f1676ebbe0016771ef50b6001d\" ],\r\n  \"cUserName\" : [ \"王海森\" ],\r\n  \"cDate\" : [ \"2020-07-13\" ],\r\n  \"longtermMeasure\" : [ \"老旧仪器分配相应负责人，每三个小时检查仪器运作情况并记录上报\" ],\r\n  \"lUserId\" : [ \"2c93b4f1676ebbe0016771ef50b6001d\" ],\r\n  \"lUserName\" : [ \"王海森\" ],\r\n  \"lDate\" : [ \"2020-07-13\" ],\r\n  \"implementationEffect\" : [ \"效果不错，大大提高了品控质量。\" ],\r\n  \"eUserId\" : [ \"2c93b4f1676ebbe0016771ef50b6001d\" ],\r\n  \"eUserName\" : [ \"王海森\" ],\r\n  \"eDate\" : [ \"2020-07-15\" ],\r\n  \"agreeClose\" : [ \"同一\" ],\r\n  \"aUserId\" : [ \"2c93b4f16bb1e070016bd5752f110397\" ],\r\n  \"aUserName\" : [ \"徐丽霞\" ],\r\n  \"aDate\" : [ \"2020-07-15\" ]\r\n}",
            "status": 0,
            "errorMsg": null,
            "operTime": "2020-07-13 16:33:21"
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": null,
            "createTime": null,
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "operId": 2382,
            "title": "投诉单",
            "businessType": 1,
            "businessTypes": null,
            "method": "com.qcp.complain.controller.ComplaintInvoiceController.addSave()",
            "operatorType": 1,
            "operName": "admin",
            "deptName": "上海益吉",
            "operUrl": "/sqm-admin/complain/complaintInvoice/add",
            "operIp": "223.166.81.134",
            "operLocation": "XX XX",
            "operParam": "{\r\n  \"invoiceId\" : [ \"\" ],\r\n  \"invoiceNo\" : [ \"\" ],\r\n  \"partId\" : [ \"9cf23272c4db11ea9c0b00163e1ae183\" ],\r\n  \"part.partName\" : [ \"滤清器\" ],\r\n  \"part.specification\" : [ \"210*270\" ],\r\n  \"batchNo\" : [ \"P20200-0715-1/2\" ],\r\n  \"supplierId\" : [ \"02cd6e9df95511e98b0300163e1ae183\" ],\r\n  \"supplier.supplierNo\" : [ \"C1002\" ],\r\n  \"supplier.supplierName\" : [ \"上海达克罗涂复工业有限公司\" ],\r\n  \"findTime\" : [ \"2020-07-13\" ],\r\n  \"createStage\" : [ \"1\" ],\r\n  \"invoiceDate\" : [ \"2020-07-13\" ],\r\n  \"planFinishDate\" : [ \"2020-07-15\" ],\r\n  \"inspectNum\" : [ \"5\" ],\r\n  \"rejectNum\" : [ \"3\" ],\r\n  \"rejectRatio\" : [ \"1.0\" ],\r\n  \"apprUserId\" : [ \"2c93b4f16bb1e070016bd5752f110397\" ],\r\n  \"apprUserName\" : [ \"徐丽霞\" ],\r\n  \"disqualificationDescription\" : [ \"滤清器抽检中长度不合格，超出允许范围\" ],\r\n  \"provisionalMeasures\" : [ \"对应的几台生产仪器已停产，调试员正进行调试\" ],\r\n  \"pUserId\" : [ \"2c93b4f1676ebbe0016771ef50b6001d\" ],\r\n  \"pUserName\" : [ \"王海森\" ],\r\n  \"pDate\" : [ \"2020-07-13\" ],\r\n  \"primaryCause\" : [ \"生产仪器老化\" ],\r\n  \"cUserId\" : [ \"2c93b4f1676ebbe0016771ef50b6001d\" ],\r\n  \"cUserName\" : [ \"王海森\" ],\r\n  \"cDate\" : [ \"2020-07-13\" ],\r\n  \"longtermMeasure\" : [ \"老旧仪器分配相应负责人，每三个小时检查仪器运作情况并记录上报\" ],\r\n  \"lUserId\" : [ \"2c93b4f1676ebbe0016771ef50b6001d\" ],\r\n  \"lUserName\" : [ \"王海森\" ],\r\n  \"lDate\" : [ \"2020-07-13\" ],\r\n  \"implementationEffect\" : [ \"效果不错，大大提高了品控质量。\" ],\r\n  \"eUserId\" : [ \"2c93b4f1676ebbe0016771ef50b6001d\" ],\r\n  \"eUserName\" : [ \"王海森\" ],\r\n  \"eDate\" : [ \"2020-07-15\" ],\r\n  \"agreeClose\" : [ \"同一\" ],\r\n  \"aUserId\" : [ \"2c93b4f16bb1e070016bd5752f110397\" ],\r\n  \"aUserName\" : [ \"徐丽霞\" ],\r\n  \"aDate\" : [ \"2020-07-15\" ]\r\n}",
            "status": 0,
            "errorMsg": null,
            "operTime": "2020-07-13 16:31:49"
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": null,
            "createTime": null,
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "operId": 2381,
            "title": "不合格评审单",
            "businessType": 1,
            "businessTypes": null,
            "method": "com.qcp.iqc.controller.DisqualificationReviewController.addSave()",
            "operatorType": 1,
            "operName": "admin",
            "deptName": "上海益吉",
            "operUrl": "/sqm-admin/iqc/disqualificationReview/add",
            "operIp": "223.166.81.134",
            "operLocation": "XX XX",
            "operParam": "{\r\n  \"inspectionId\" : [ \"19158e5bc4df11ea9c0b00163e1ae183\" ],\r\n  \"inspectionNo\" : [ \"IQC-20200713-0001\" ],\r\n  \"reviewNo\" : [ \"MRB- IQC-20200713-0001\" ],\r\n  \"partName\" : [ \"滤清器\" ],\r\n  \"partId\" : [ \"9cf23272c4db11ea9c0b00163e1ae183\" ],\r\n  \"materials\" : [ \"不锈钢、铜、钛、活性炭、高聚物\" ],\r\n  \"specification\" : [ \"210*270\" ],\r\n  \"batchNo\" : [ \"P20200-0715-1/2\" ],\r\n  \"findTime\" : [ \"2020-07-13\" ],\r\n  \"startTime\" : [ \"2020-07-12\" ],\r\n  \"createTimeStart\" : [ \"2020-07-12\" ],\r\n  \"createTimeEnd\" : [ \"2020-07-13\" ],\r\n  \"inspectNum\" : [ \"5\" ],\r\n  \"rejectNum\" : [ \"3\" ],\r\n  \"rejectRatio\" : [ \"1.0\" ],\r\n  \"horizontalTraceability\" : [ \"0\" ],\r\n  \"suspectedNum\" : [ \"2\" ],\r\n  \"accumulativeRejectNum\" : [ \"5\" ],\r\n  \"userName\" : [ \"徐丽霞\" ],\r\n  \"userId\" : [ \"2c93b4f16bb1e070016bd5752f110397\" ],\r\n  \"productResponsibleUser\" : [ \"王海森\" ],\r\n  \"qualityResponsibleUser\" : [ \"王海森\" ],\r\n  \"findSite\" : [ \"0\" ],\r\n  \"disqualificationDescription\" : [ \"检验项目：宝来滤清器\\r\\n检验类别：长\\r\\n标准值：<11mm\\r\\n检验值：13、10、11、9、13、\\r\\n检验结果： 不合格\" ],\r\n  \"responsibleDept\" : [ \"来料检验部\" ],\r\n  \"dUserName\" : [ \"徐丽霞\" ],\r\n  \"dUserId\" : [ \"2c93b4f16bb1e070016bd5752f110397\" ],\r\n  \"dDate\" : [ \"2020-07-15\" ],\r\n  \"rejectReason\" : [ \"生产仪器出现突发性故障，故有残次品流入在内\" ],\r\n  \"improvementMeasure\" : [ \"技术员对仪器进行调试\" ],\r\n  \"pUserName\" : [ \"欧添\" ],\r\n  \"pUserId\" : [ \"2c93b4f167a2e5060167a6b5c10400f6\" ],\r\n  \"pDate\" : [ \"2020-07-13\" ],\r\n  \"craftRational\" : [ \"0\" ],\r\n  \"craftAdjustment\" : [ \"1\" ],\r\n  \"adjustedState\" : [ \"正常\" ],\r\n  \"newCraftStartTime\" : [ \"2020-07-13\" ],\r\n  \"productionTreatmentPlan\" : [ \"回收销毁\" ],\r\n  \"eUserName\" : [ \"杨彪\" ],\r\n  \"eUserId\" : [ \"2c93b4f16774ac33016776e5fa72000d\" ],\r\n  \"eDate\" : [ \"2020-07-13\" ],\r\n  \"affectShipment\" : [ \"1\" ],\r\n  \"needReplenishment\" : [ \"1\" ],\r\n  \"bScheme\" : [ \"建议每台生产仪器配备一名相应负责人随时检查生产情况\" ],\r\n  \"bUserName\" : [ \"宋江\" ],\r\n  \"bUserId\" : [ \"2c93b4f16782a1bf0167a6b3aff707ce\" ],\r\n  \"bDate\" : [ \"2020-07-13\" ],\r\n  \"fOpinion\" : [ \"需严格把控好仪器生产效率及质量，出现问题及时发现早处理。\" ],\r\n  \"conductAssess\" : [ \"0\" ],\r\n  \"fUserName\" : [ \"高文雅\" ],\r\n  \"fUserId\" : [ \"2c93b4f169066",
            "status": 0,
            "errorMsg": null,
            "operTime": "2020-07-13 16:23:27"
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": null,
            "createTime": null,
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "operId": 2380,
            "title": "采购单",
            "businessType": 2,
            "businessTypes": null,
            "method": "com.qcp.iqc.controller.PurchaseController.editSave()",
            "operatorType": 1,
            "operName": "admin",
            "deptName": "上海益吉",
            "operUrl": "/sqm-admin/iqc/purchase/edit",
            "operIp": "223.166.81.134",
            "operLocation": "XX XX",
            "operParam": "{\r\n  \"purchaseId\" : [ \"a9b1b40ac4de11ea9c0b00163e1ae183\" ],\r\n  \"purchaseNo\" : [ \"CGD20200713\" ],\r\n  \"supplierNo\" : [ \"C1002\" ],\r\n  \"supplierId\" : [ \"02cd6e9df95511e98b0300163e1ae183\" ],\r\n  \"supplierName\" : [ \"上海达克罗涂复工业有限公司\" ],\r\n  \"purchaseDate\" : [ \"2020-07-13\" ],\r\n  \"userNo\" : [ \"admin\" ],\r\n  \"userName\" : [ \"admin\" ],\r\n  \"userId\" : [ \"admin\" ],\r\n  \"state\" : [ \"0\" ],\r\n  \"materialCoding0\" : [ \"ERP-071301\" ],\r\n  \"partName0\" : [ \"滤清器\" ],\r\n  \"specification0\" : [ \"210*270\" ],\r\n  \"totalNum0\" : [ \"1000\" ],\r\n  \"unitPrice0\" : [ \"320\" ],\r\n  \"totalPrice0\" : [ \"320000\" ],\r\n  \"deliveryDate0\" : [ \"2020-07-13\" ],\r\n  \"replyDate0\" : [ \"2020-07-13\" ],\r\n  \"materialCoding1\" : [ \"ERP-071302\" ],\r\n  \"partName1\" : [ \"螺母\" ],\r\n  \"specification1\" : [ \"3mm\" ],\r\n  \"totalNum1\" : [ \"500\" ],\r\n  \"unitPrice1\" : [ \"80\" ],\r\n  \"totalPrice1\" : [ \"40000\" ],\r\n  \"deliveryDate1\" : [ \"2020-07-13\" ],\r\n  \"replyDate1\" : [ \"2020-07-13\" ],\r\n  \"list\" : [ \"[{\\\"companyId\\\":\\\"402880e762656861016266cc46140049\\\",\\\"companyName\\\":null,\\\"searchValue\\\":null,\\\"createBy\\\":null,\\\"createTime\\\":null,\\\"updateBy\\\":null,\\\"updateTime\\\":null,\\\"createUserName\\\":\\\"admin\\\",\\\"updateUserName\\\":null,\\\"remark\\\":null,\\\"deleteFlag\\\":\\\"0\\\",\\\"createUserId\\\":\\\"admin\\\",\\\"createDate\\\":\\\"2020-07-13 15:58:41\\\",\\\"updateUserId\\\":null,\\\"updateDate\\\":null,\\\"params\\\":{},\\\"detailId\\\":\\\"a9b4399fc4de11ea9c0b00163e1ae183\\\",\\\"purchaseId\\\":\\\"a9b1b40ac4de11ea9c0b00163e1ae183\\\",\\\"materialCoding\\\":\\\"ERP-071301\\\",\\\"partId\\\":\\\"9cf23272c4db11ea9c0b00163e1ae183\\\",\\\"partName\\\":\\\"滤清器\\\",\\\"specification\\\":\\\"210*270\\\",\\\"totalNum\\\":1000,\\\"unit\\\":\\\"0\\\",\\\"unitPrice\\\":320,\\\"totalPrice\\\":320000,\\\"deliveryDate\\\":\\\"2020-07-13\\\",\\\"replyDate\\\":\\\"2020-07-13\\\",\\\"isTaxIncluded\\\":\\\"0\\\",\\\"proIndex\\\":0,\\\"undefined\\\":true},{\\\"companyId\\\":\\\"402880e762656861016266cc46140049\\\",\\\"companyName\\\":null,\\\"searchValue\\\":null,\\\"createBy\\\":null,\\\"createTime\\\":null,\\\"updateBy\\\":null,\\\"updateTime\\\":null,\\\"createUserName\\\":\\\"admin\\\",\\\"updateUserName\\\":null,\\\"remark\\\":null,\\\"deleteFlag\\\":\\\"0\\\",\\\"create",
            "status": 0,
            "errorMsg": null,
            "operTime": "2020-07-13 16:13:49"
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": null,
            "createTime": null,
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "operId": 2379,
            "title": "来料检验单",
            "businessType": 2,
            "businessTypes": null,
            "method": "com.qcp.iqc.controller.IncomingInspectionController.editSave()",
            "operatorType": 1,
            "operName": "admin",
            "deptName": "上海益吉",
            "operUrl": "/sqm-admin/iqc/incomingInspection/edit",
            "operIp": "223.166.81.134",
            "operLocation": "XX XX",
            "operParam": "{\r\n  \"inspectionId\" : [ \"19158e5bc4df11ea9c0b00163e1ae183\" ],\r\n  \"inspectionNo\" : [ \"IQC-20200713-0001\" ],\r\n  \"resultValue10\" : [ \"4\" ],\r\n  \"resultValue20\" : [ \"2\" ],\r\n  \"resultValue30\" : [ \"9\" ],\r\n  \"resultValue40\" : [ \"10\" ],\r\n  \"resultValue50\" : [ \"12\" ],\r\n  \"resultValue11\" : [ \"13\" ],\r\n  \"resultValue21\" : [ \"10\" ],\r\n  \"resultValue31\" : [ \"11\" ],\r\n  \"resultValue41\" : [ \"9\" ],\r\n  \"resultValue51\" : [ \"13\" ],\r\n  \"determine\" : [ \"1\" ],\r\n  \"environmental\" : [ \"0\" ],\r\n  \"environmentalProtectionLabel\" : [ \"0\" ],\r\n  \"rejectRatio\" : [ \"1\" ],\r\n  \"inspectUserName\" : [ \"徐丽霞\" ],\r\n  \"inspectUserId\" : [ \"2c93b4f16bb1e070016bd5752f110397\" ],\r\n  \"storeUserName\" : [ \"admin\" ],\r\n  \"storeUserId\" : [ \"admin\" ],\r\n  \"materialApproval\" : [ \"陈丽娟\" ],\r\n  \"qualityApproval\" : [ \"徐丽霞\" ],\r\n  \"state\" : [ \"1\" ],\r\n  \"remark\" : [ \"7月15号第一批滤清器长度抽检不合格，来料数量500，抽检数量5\" ],\r\n  \"list\" : [ \"[{\\\"companyId\\\":\\\"402880e762656861016266cc46140049\\\",\\\"companyName\\\":null,\\\"searchValue\\\":null,\\\"createBy\\\":null,\\\"createTime\\\":null,\\\"updateBy\\\":null,\\\"updateTime\\\":null,\\\"createUserName\\\":\\\"admin\\\",\\\"updateUserName\\\":null,\\\"remark\\\":null,\\\"deleteFlag\\\":null,\\\"createUserId\\\":\\\"admin\\\",\\\"createDate\\\":\\\"2020-07-13 16:01:47\\\",\\\"updateUserId\\\":null,\\\"updateDate\\\":null,\\\"params\\\":{},\\\"detailId\\\":\\\"1919d6e2c4df11ea9c0b00163e1ae183\\\",\\\"inspectionId\\\":\\\"19158e5bc4df11ea9c0b00163e1ae183\\\",\\\"standardId\\\":\\\"7b06c000c4dd11ea9c0b00163e1ae183\\\",\\\"inspectionItem\\\":\\\"宝来滤清器\\\",\\\"inspectionType\\\":\\\"直径\\\",\\\"tolerances\\\":\\\"<10mm\\\",\\\"determine\\\":\\\"0\\\",\\\"picture\\\":null,\\\"resultList\\\":[{\\\"companyId\\\":\\\"402880e762656861016266cc46140049\\\",\\\"companyName\\\":null,\\\"searchValue\\\":null,\\\"createBy\\\":null,\\\"createTime\\\":null,\\\"updateBy\\\":null,\\\"updateTime\\\":null,\\\"createUserName\\\":\\\"admin\\\",\\\"updateUserName\\\":null,\\\"remark\\\":null,\\\"deleteFlag\\\":null,\\\"createUserId\\\":\\\"admin\\\",\\\"createDate\\\":\\\"2020-07-13 16:01:47\\\",\\\"updateUserId\\\":null,\\\"updateDate\\\":null,\\\"params\\\":{},\\\"resultId\\\":\\\"191bf80cc4df11ea9c0b00163e1ae183\\\",\\\"detailId\\\":\\\"1919d6e2c4df11ea9c0b",
            "status": 0,
            "errorMsg": null,
            "operTime": "2020-07-13 16:08:26"
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": null,
            "createTime": null,
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "operId": 2378,
            "title": "来料检验单",
            "businessType": 1,
            "businessTypes": null,
            "method": "com.qcp.iqc.controller.IncomingInspectionController.addSave()",
            "operatorType": 1,
            "operName": "admin",
            "deptName": "上海益吉",
            "operUrl": "/sqm-admin/iqc/incomingInspection/add",
            "operIp": "223.166.81.134",
            "operLocation": "XX XX",
            "operParam": "{\r\n  \"purchaseNo\" : [ \"CGD20200713\" ],\r\n  \"purchaseId\" : [ \"a9b1b40ac4de11ea9c0b00163e1ae183\" ],\r\n  \"purchaseDetailId\" : [ \"a9b4399fc4de11ea9c0b00163e1ae183\" ],\r\n  \"code\" : [ \"ERP-071301\" ],\r\n  \"supplierNo\" : [ \"C1002\" ],\r\n  \"supplierId\" : [ \"02cd6e9df95511e98b0300163e1ae183\" ],\r\n  \"supplierName\" : [ \"上海达克罗涂复工业有限公司\" ],\r\n  \"partName\" : [ \"滤清器\" ],\r\n  \"partId\" : [ \"9cf23272c4db11ea9c0b00163e1ae183\" ],\r\n  \"materials\" : [ \"不锈钢、铜、钛、活性炭、高聚物\" ],\r\n  \"specification\" : [ \"210*270\" ],\r\n  \"standardId\" : [ \"7b06c000c4dd11ea9c0b00163e1ae183\" ],\r\n  \"batchNo\" : [ \"P20200-0715-1/2\" ],\r\n  \"incomingNum\" : [ \"500\" ],\r\n  \"inspectNum\" : [ \"5\" ]\r\n}",
            "status": 0,
            "errorMsg": null,
            "operTime": "2020-07-13 16:01:48"
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": null,
            "createTime": null,
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "operId": 2377,
            "title": "采购单",
            "businessType": 1,
            "businessTypes": null,
            "method": "com.qcp.iqc.controller.PurchaseController.addSave()",
            "operatorType": 1,
            "operName": "admin",
            "deptName": "上海益吉",
            "operUrl": "/sqm-admin/iqc/purchase/add",
            "operIp": "223.166.81.134",
            "operLocation": "XX XX",
            "operParam": "{\r\n  \"purchaseNo\" : [ \"CGD20200713\" ],\r\n  \"purchaseType\" : [ \"0\" ],\r\n  \"supplierNo\" : [ \"C1002\" ],\r\n  \"supplierId\" : [ \"02cd6e9df95511e98b0300163e1ae183\" ],\r\n  \"supplierName\" : [ \"上海达克罗涂复工业有限公司\" ],\r\n  \"purchaseDate\" : [ \"2020-07-13\" ],\r\n  \"userNo\" : [ \"admin\" ],\r\n  \"userName\" : [ \"admin\" ],\r\n  \"userId\" : [ \"admin\" ],\r\n  \"state\" : [ \"0\" ],\r\n  \"materialCoding0\" : [ \"ERP-071301\" ],\r\n  \"partName0\" : [ \"滤清器\" ],\r\n  \"specification0\" : [ \"210*270\" ],\r\n  \"totalNum0\" : [ \"1000\" ],\r\n  \"unitPrice0\" : [ \"320\" ],\r\n  \"totalPrice0\" : [ \"320000\" ],\r\n  \"deliveryDate0\" : [ \"2020-07-15\" ],\r\n  \"replyDate0\" : [ \"2020-07-13\" ],\r\n  \"materialCoding1\" : [ \"ERP-071302\" ],\r\n  \"partName1\" : [ \"螺母\" ],\r\n  \"specification1\" : [ \"3mm\" ],\r\n  \"totalNum1\" : [ \"500\" ],\r\n  \"unitPrice1\" : [ \"80\" ],\r\n  \"totalPrice1\" : [ \"40000\" ],\r\n  \"deliveryDate1\" : [ \"2020-07-16\" ],\r\n  \"replyDate1\" : [ \"2020-07-13\" ],\r\n  \"list\" : [ \"[{\\\"proIndex\\\":0,\\\"materialCoding\\\":\\\"ERP-071301\\\",\\\"partId\\\":\\\"9cf23272c4db11ea9c0b00163e1ae183\\\",\\\"partName\\\":\\\"滤清器\\\",\\\"specification\\\":\\\"210*270\\\",\\\"totalNum\\\":\\\"1000\\\",\\\"unit\\\":\\\"0\\\",\\\"unitPrice\\\":\\\"320\\\",\\\"isTaxIncluded\\\":\\\"0\\\",\\\"totalPrice\\\":320000,\\\"deliveryDate\\\":\\\"2020-07-15\\\",\\\"replyDate\\\":\\\"2020-07-13\\\",\\\"operate\\\":\\\"\\\",\\\"undefined\\\":true,\\\"materials\\\":\\\"不锈钢、铜、钛、活性炭、高聚物\\\"},{\\\"proIndex\\\":1,\\\"materialCoding\\\":\\\"ERP-071302\\\",\\\"partId\\\":\\\"27ea9c22f97011e98b0300163e1ae183\\\",\\\"partName\\\":\\\"螺母\\\",\\\"specification\\\":\\\"3mm\\\",\\\"totalNum\\\":\\\"500\\\",\\\"unit\\\":\\\"2\\\",\\\"unitPrice\\\":\\\"80\\\",\\\"isTaxIncluded\\\":\\\"0\\\",\\\"totalPrice\\\":40000,\\\"deliveryDate\\\":\\\"2020-07-16\\\",\\\"replyDate\\\":\\\"2020-07-13\\\",\\\"operate\\\":\\\"\\\",\\\"undefined\\\":true,\\\"materials\\\":\\\"合金\\\"}]\" ]\r\n}",
            "status": 0,
            "errorMsg": null,
            "operTime": "2020-07-13 15:58:41"
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": null,
            "createTime": null,
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "operId": 2376,
            "title": "供应商",
            "businessType": 2,
            "businessTypes": null,
            "method": "com.qcp.web.controller.masterdata.SupplierController.editSave()",
            "operatorType": 1,
            "operName": "admin",
            "deptName": "上海益吉",
            "operUrl": "/sqm-admin/masterdata/supplier/edit",
            "operIp": "223.166.81.134",
            "operLocation": "XX XX",
            "operParam": "{\r\n  \"supplierId\" : [ \"02cd6e9df95511e98b0300163e1ae183\" ],\r\n  \"removeFileTag\" : [ \"\" ],\r\n  \"supplierNo\" : [ \"C1002\" ],\r\n  \"supplierName\" : [ \"上海达克罗涂复工业有限公司\" ],\r\n  \"supplierType\" : [ \"2\" ],\r\n  \"supplierLevel\" : [ \"0\" ],\r\n  \"state\" : [ \"0\" ],\r\n  \"position0\" : [ \"经理\" ],\r\n  \"linkmanName0\" : [ \"宋勉\" ],\r\n  \"mobile0\" : [ \"13162062572\" ],\r\n  \"email0\" : [ \"2537542901@qq.com\" ],\r\n  \"address0\" : [ \"上海市嘉定区安亭镇昌吉东路1011号\" ],\r\n  \"certificate0\" : [ \"ZL293567790013\" ],\r\n  \"startDate0\" : [ \"2019-06-06\" ],\r\n  \"endingDate0\" : [ \"2024-07-31\" ],\r\n  \"finishUserName0\" : [ \"admin\" ],\r\n  \"lateFinishDate0\" : [ \"2020-11-13\" ],\r\n  \"remindUserName0\" : [ \"admin\" ],\r\n  \"remindDeadline0\" : [ \"10\" ],\r\n  \"supplierQualifications\" : [ \"[{\\\"proIndex\\\":0,\\\"category\\\":\\\"0\\\",\\\"name\\\":\\\"0\\\",\\\"fileType\\\":\\\"1\\\",\\\"certificate\\\":\\\"ZL293567790013\\\",\\\"startDate\\\":\\\"2019-06-06\\\",\\\"endingDate\\\":\\\"2024-07-31\\\",\\\"finishUserId\\\":\\\"admin\\\",\\\"finishUserName\\\":\\\"admin\\\",\\\"lateFinishDate\\\":\\\"2020-11-13\\\",\\\"remindUserId\\\":\\\"admin\\\",\\\"remindUserName\\\":\\\"admin\\\",\\\"remindDeadline\\\":\\\"10\\\",\\\"validity\\\":\\\"0\\\",\\\"state\\\":\\\"0\\\",\\\"undefined\\\":true}]\" ],\r\n  \"supplierLinkmans\" : [ \"[{\\\"proIndex\\\":0,\\\"defaultFlag\\\":\\\"1\\\",\\\"defaultFlags\\\":\\\"是\\\",\\\"position\\\":\\\"经理\\\",\\\"linkmanName\\\":\\\"宋勉\\\",\\\"mobile\\\":\\\"13162062572\\\",\\\"email\\\":\\\"2537542901@qq.com\\\",\\\"address\\\":\\\"上海市嘉定区安亭镇昌吉东路1011号\\\",\\\"undefined\\\":true}]\" ],\r\n  \"fileDataId\" : [ \"\" ]\r\n}",
            "status": 0,
            "errorMsg": null,
            "operTime": "2020-07-13 15:56:13"
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": null,
            "createTime": null,
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "operId": 2375,
            "title": "检验标准",
            "businessType": 1,
            "businessTypes": null,
            "method": "com.qcp.web.controller.masterdata.InspectionStandardController.addSave()",
            "operatorType": 1,
            "operName": "admin",
            "deptName": "上海益吉",
            "operUrl": "/sqm-admin/masterdata/inspectionStandard/add",
            "operIp": "223.166.81.134",
            "operLocation": "XX XX",
            "operParam": "{\r\n  \"standardNo\" : [ \"JYBZ-2020713\" ],\r\n  \"supplierId\" : [ \"02cd6e9df95511e98b0300163e1ae183\" ],\r\n  \"supplierNo\" : [ \"C1002\" ],\r\n  \"supplierName\" : [ \"上海达克罗涂复工业有限公司\" ],\r\n  \"partId\" : [ \"9cf23272c4db11ea9c0b00163e1ae183\" ],\r\n  \"partNo\" : [ \"AutoFilter-2020713\" ],\r\n  \"partName\" : [ \"滤清器\" ],\r\n  \"specification\" : [ \"210*270\" ],\r\n  \"materials\" : [ \"不锈钢、铜、钛、活性炭、高聚物\" ],\r\n  \"state\" : [ \"0\" ],\r\n  \"inspectionItem0\" : [ \"宝来滤清器\" ],\r\n  \"inspectionType0\" : [ \"直径\" ],\r\n  \"tolerances0\" : [ \"<10mm\" ],\r\n  \"inspectionItem1\" : [ \"宝来滤清器\" ],\r\n  \"inspectionType1\" : [ \"长\" ],\r\n  \"tolerances1\" : [ \"<11mm\" ],\r\n  \"inspectionStandardDetail\" : [ \"[{\\\"proIndex\\\":0,\\\"inspectionItem\\\":\\\"宝来滤清器\\\",\\\"inspectionType\\\":\\\"直径\\\",\\\"tolerances\\\":\\\"<10mm\\\",\\\"state\\\":\\\"0\\\",\\\"undefined\\\":true},{\\\"proIndex\\\":1,\\\"inspectionItem\\\":\\\"宝来滤清器\\\",\\\"inspectionType\\\":\\\"长\\\",\\\"tolerances\\\":\\\"<11mm\\\",\\\"state\\\":\\\"0\\\",\\\"undefined\\\":true}]\" ]\r\n}",
            "status": 0,
            "errorMsg": null,
            "operTime": "2020-07-13 15:50:43"
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": null,
            "createTime": null,
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "operId": 2374,
            "title": "检验标准",
            "businessType": 3,
            "businessTypes": null,
            "method": "com.qcp.web.controller.masterdata.InspectionStandardController.remove()",
            "operatorType": 1,
            "operName": "admin",
            "deptName": "上海益吉",
            "operUrl": "/sqm-admin/masterdata/inspectionStandard/remove",
            "operIp": "223.166.81.134",
            "operLocation": "XX XX",
            "operParam": "{\r\n  \"ids\" : [ \"30d5fb8bf95511e98b0300163e1ae183\" ]\r\n}",
            "status": 0,
            "errorMsg": null,
            "operTime": "2020-07-13 15:41:05"
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": null,
            "createTime": null,
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "operId": 2373,
            "title": "零件",
            "businessType": 2,
            "businessTypes": null,
            "method": "com.qcp.web.controller.masterdata.PartController.editSave()",
            "operatorType": 1,
            "operName": "admin",
            "deptName": "上海益吉",
            "operUrl": "/sqm-admin/masterdata/part/edit",
            "operIp": "223.166.81.134",
            "operLocation": "XX XX",
            "operParam": "{\r\n  \"partId\" : [ \"d0be3d97f97011e98b0300163e1ae183\" ],\r\n  \"removeFileTag\" : [ \"1\" ],\r\n  \"version\" : [ \"A1\" ],\r\n  \"partNo\" : [ \"LJH-1028-01\" ],\r\n  \"partName\" : [ \"转轴\" ],\r\n  \"specification\" : [ \"GG-10*28-01\" ],\r\n  \"materials\" : [ \"不锈钢、铜\" ],\r\n  \"partType\" : [ \"0\" ],\r\n  \"state\" : [ \"0\" ],\r\n  \"remark\" : [ \"生产制造出来后可以直接使用，并不会有什么大的问题的。\" ],\r\n  \"clientNo0\" : [ \"ZHUANZHOU-KEHU-01\" ],\r\n  \"clientName0\" : [ \"张晓\" ],\r\n  \"clientNo1\" : [ \"ZHUANZHOU-KEHU-02\" ],\r\n  \"clientName1\" : [ \"李华\" ],\r\n  \"clientNo2\" : [ \"ZHUANZHOU-KEHU-03\" ],\r\n  \"clientName2\" : [ \"王友华\" ],\r\n  \"recordContent\" : [ \"修改了供应商\" ],\r\n  \"approverId\" : [ \"2c93b4f16bb1e070016bd5752f110397\" ],\r\n  \"approverName\" : [ \"徐丽霞\" ],\r\n  \"partClients\" : [ \"[{\\\"proIndex\\\":0,\\\"clientNo\\\":\\\"ZHUANZHOU-KEHU-01\\\",\\\"clientName\\\":\\\"张晓\\\",\\\"undefined\\\":true},{\\\"proIndex\\\":1,\\\"clientNo\\\":\\\"ZHUANZHOU-KEHU-02\\\",\\\"clientName\\\":\\\"李华\\\",\\\"undefined\\\":true},{\\\"proIndex\\\":2,\\\"clientNo\\\":\\\"ZHUANZHOU-KEHU-03\\\",\\\"clientName\\\":\\\"王友华\\\",\\\"undefined\\\":true}]\" ]\r\n}",
            "status": 0,
            "errorMsg": null,
            "operTime": "2020-07-13 15:39:13"
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": null,
            "createTime": null,
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "operId": 2372,
            "title": "零件",
            "businessType": 1,
            "businessTypes": null,
            "method": "com.qcp.web.controller.masterdata.PartController.addSave()",
            "operatorType": 1,
            "operName": "admin",
            "deptName": "上海益吉",
            "operUrl": "/sqm-admin/masterdata/part/add",
            "operIp": "223.166.81.134",
            "operLocation": "XX XX",
            "operParam": "{\r\n  \"partNo\" : [ \"AutoFilter-2020713\" ],\r\n  \"partName\" : [ \"滤清器\" ],\r\n  \"specification\" : [ \"210*270\" ],\r\n  \"materials\" : [ \"不锈钢、铜、钛、活性炭、高聚物\" ],\r\n  \"partType\" : [ \"2\" ],\r\n  \"state\" : [ \"0\" ],\r\n  \"remark\" : [ \"机油滤清器\" ],\r\n  \"clientNo0\" : [ \"YF0713\" ],\r\n  \"clientName0\" : [ \"周鑫\" ],\r\n  \"clientNo1\" : [ \"YM0829\" ],\r\n  \"clientName1\" : [ \"王友华\" ],\r\n  \"partClients\" : [ \"[{\\\"proIndex\\\":0,\\\"clientNo\\\":\\\"YF0713\\\",\\\"clientName\\\":\\\"周鑫\\\",\\\"undefined\\\":true},{\\\"proIndex\\\":1,\\\"clientNo\\\":\\\"YM0829\\\",\\\"clientName\\\":\\\"王友华\\\",\\\"undefined\\\":true}]\" ]\r\n}",
            "status": 0,
            "errorMsg": null,
            "operTime": "2020-07-13 15:36:51"
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": null,
            "createTime": null,
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "operId": 2371,
            "title": "年度计划",
            "businessType": 2,
            "businessTypes": null,
            "method": "com.qcp.sysman.controller.AuditPlanController.resultInputSave()",
            "operatorType": 1,
            "operName": "13795240575",
            "deptName": "上海益吉(内部)",
            "operUrl": "/sqm-admin/sysman/auditPlan/resultInputSave",
            "operIp": "223.166.81.134",
            "operLocation": "XX XX",
            "operParam": "{\r\n  \"planId\" : [ \"5cd8dc2ac4d611ea9c0b00163e1ae183\" ],\r\n  \"auditResult\" : [ \"98\" ],\r\n  \"auditFinishDate\" : [ \"2020-07-09\" ],\r\n  \"nextAuditDate\" : [ \"2021-07-09\" ],\r\n  \"reformFinishDate\" : [ \"2020-10-09\" ],\r\n  \"inconNum\" : [ \"1\" ],\r\n  \"actualAdvice\" : [ \"通过\" ]\r\n}",
            "status": 0,
            "errorMsg": null,
            "operTime": "2020-07-13 15:22:08"
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": null,
            "createTime": null,
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "operId": 2370,
            "title": "年度计划",
            "businessType": 10,
            "businessTypes": null,
            "method": "com.qcp.sysman.controller.AuditPlanController.projectApprSave()",
            "operatorType": 1,
            "operName": "13795240575",
            "deptName": "上海益吉(内部)",
            "operUrl": "/sqm-admin/sysman/auditPlan/projectApprSave",
            "operIp": "223.166.81.134",
            "operLocation": "XX XX",
            "operParam": "{\r\n  \"approvalState\" : [ \"0\" ],\r\n  \"approvalAdvice\" : [ \"\" ],\r\n  \"dataId\" : [ \"5cd8dc2ac4d611ea9c0b00163e1ae183\" ],\r\n  \"dataFlag\" : [ \"auditPlan.projectAppr\" ]\r\n}",
            "status": 0,
            "errorMsg": null,
            "operTime": "2020-07-13 15:18:57"
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": null,
            "createTime": null,
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "operId": 2369,
            "title": "零件",
            "businessType": 3,
            "businessTypes": null,
            "method": "com.qcp.web.controller.masterdata.PartController.remove()",
            "operatorType": 1,
            "operName": "13795240575",
            "deptName": "上海益吉(内部)",
            "operUrl": "/sqm-admin/masterdata/part/remove",
            "operIp": "223.166.81.134",
            "operLocation": "XX XX",
            "operParam": "{\r\n  \"ids\" : [ \"19c2826cf95511e98b0300163e1ae183\" ]\r\n}",
            "status": 0,
            "errorMsg": null,
            "operTime": "2020-07-13 15:18:50"
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": null,
            "createTime": null,
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "operId": 2368,
            "title": "供应商",
            "businessType": 3,
            "businessTypes": null,
            "method": "com.qcp.web.controller.masterdata.SupplierController.remove()",
            "operatorType": 1,
            "operName": "13795240575",
            "deptName": "上海益吉(内部)",
            "operUrl": "/sqm-admin/masterdata/supplier/remove",
            "operIp": "223.166.81.134",
            "operLocation": "XX XX",
            "operParam": "{\r\n  \"ids\" : [ \"c65e2c45053411ea8b0300163e1ae183\" ]\r\n}",
            "status": 0,
            "errorMsg": null,
            "operTime": "2020-07-13 15:17:27"
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": null,
            "createTime": null,
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "operId": 2367,
            "title": "审核计划",
            "businessType": 1,
            "businessTypes": null,
            "method": "com.qcp.sysman.controller.AuditPlanController.addSave()",
            "operatorType": 1,
            "operName": "15502169523",
            "deptName": "上海益吉",
            "operUrl": "/sqm-admin/sysman/auditPlan/add",
            "operIp": "223.166.81.134",
            "operLocation": "XX XX",
            "operParam": "{\r\n  \"planId\" : [ \"\" ],\r\n  \"supplierId\" : [ \"63fba9f6c4d311ea9c0b00163e1ae183\" ],\r\n  \"supplier.supplierNo\" : [ \"延锋汽车\" ],\r\n  \"supplier.supplierName\" : [ \"10023\" ],\r\n  \"reviewCategory\" : [ \"0\" ],\r\n  \"quaCategory\" : [ \"1\" ],\r\n  \"quaName\" : [ \"0\" ],\r\n  \"cerValidityStart\" : [ \"2020-07-07\" ],\r\n  \"cerValidityEnd\" : [ \"2020-08-14\" ],\r\n  \"linkmanName\" : [ \"张燕\" ],\r\n  \"email\" : [ \"xulixia@imonsoft.com\" ],\r\n  \"address\" : [ \"墨玉路\" ],\r\n  \"mainProducts\" : [ \"座椅\" ],\r\n  \"reviewWay\" : [ \"0\" ],\r\n  \"projectApprUserId\" : [ \"2c93b4f16bb1e070016bd5752f110397\" ],\r\n  \"projectApprUserName\" : [ \"徐丽霞\" ],\r\n  \"resultApprUserId\" : [ \"2c93b4f16bb1e070016bd5752f110397\" ],\r\n  \"resultApprUserName\" : [ \"徐丽霞\" ]\r\n}",
            "status": 0,
            "errorMsg": null,
            "operTime": "2020-07-13 14:59:16"
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": null,
            "createTime": null,
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "operId": 2366,
            "title": "供应商",
            "businessType": 2,
            "businessTypes": null,
            "method": "com.qcp.web.controller.masterdata.SupplierController.editSave()",
            "operatorType": 1,
            "operName": "15502169523",
            "deptName": "上海益吉",
            "operUrl": "/sqm-admin/masterdata/supplier/edit",
            "operIp": "223.166.81.134",
            "operLocation": "XX XX",
            "operParam": "{\r\n  \"supplierId\" : [ \"63fba9f6c4d311ea9c0b00163e1ae183\" ],\r\n  \"removeFileTag\" : [ \"\" ],\r\n  \"supplierNo\" : [ \"延锋汽车\" ],\r\n  \"supplierName\" : [ \"10023\" ],\r\n  \"supplierType\" : [ \"1\" ],\r\n  \"supplierLevel\" : [ \"0\" ],\r\n  \"state\" : [ \"0\" ],\r\n  \"position0\" : [ \"质量总监\" ],\r\n  \"linkmanName0\" : [ \"张燕\" ],\r\n  \"mobile0\" : [ \"13978698938\" ],\r\n  \"email0\" : [ \"xulixia@imonsoft.com\" ],\r\n  \"address0\" : [ \"墨玉路\" ],\r\n  \"position1\" : [ \"质量主管\" ],\r\n  \"linkmanName1\" : [ \"刘帅\" ],\r\n  \"mobile1\" : [ \"13795240575\" ],\r\n  \"email1\" : [ \"xulixia@imonsoft.com\" ],\r\n  \"address1\" : [ \"昌吉路\" ],\r\n  \"certificate0\" : [ \"16949证书\" ],\r\n  \"startDate0\" : [ \"2020-07-01\" ],\r\n  \"endingDate0\" : [ \"2021-07-21\" ],\r\n  \"finishUserName0\" : [ \"徐丽霞\" ],\r\n  \"lateFinishDate0\" : [ \"2020-07-25\" ],\r\n  \"remindUserName0\" : [ \"徐丽霞\" ],\r\n  \"remindDeadline0\" : [ \"30\" ],\r\n  \"certificate1\" : [ \"9001\" ],\r\n  \"startDate1\" : [ \"2018-07-13\" ],\r\n  \"endingDate1\" : [ \"2019-07-25\" ],\r\n  \"finishUserName1\" : [ \"徐丽霞\" ],\r\n  \"lateFinishDate1\" : [ \"2020-07-14\" ],\r\n  \"remindUserName1\" : [ \"黄子重\" ],\r\n  \"remindDeadline1\" : [ \"14\" ],\r\n  \"supplierQualifications\" : [ \"[{\\\"proIndex\\\":0,\\\"category\\\":\\\"0\\\",\\\"name\\\":\\\"0\\\",\\\"fileType\\\":\\\"0\\\",\\\"certificate\\\":\\\"16949证书\\\",\\\"startDate\\\":\\\"2020-07-01\\\",\\\"endingDate\\\":\\\"2021-07-21\\\",\\\"finishUserId\\\":\\\"2c93b4f16bb1e070016bd5752f110397\\\",\\\"finishUserName\\\":\\\"徐丽霞\\\",\\\"lateFinishDate\\\":\\\"2020-07-25\\\",\\\"remindUserId\\\":\\\"2c93b4f16bb1e070016bd5752f110397\\\",\\\"remindUserName\\\":\\\"徐丽霞\\\",\\\"remindDeadline\\\":30,\\\"validity\\\":\\\"0\\\",\\\"state\\\":\\\"0\\\"},{\\\"proIndex\\\":1,\\\"category\\\":\\\"1\\\",\\\"name\\\":\\\"1\\\",\\\"fileType\\\":\\\"1\\\",\\\"certificate\\\":\\\"9001\\\",\\\"startDate\\\":\\\"2018-07-13\\\",\\\"endingDate\\\":\\\"2019-07-25\\\",\\\"finishUserId\\\":\\\"2c93b4f16bb1e070016bd5752f110397\\\",\\\"finishUserName\\\":\\\"徐丽霞\\\",\\\"lateFinishDate\\\":\\\"2020-07-14\\\",\\\"remindUserId\\\":\\\"0963f3da369111ea8b0300163e1ae183\\\",\\\"remindUserName\\\":\\\"黄子重\\\",\\\"remindDeadline\\\":\\\"14\\\",\\\"validity\\\":\\\"0\\\",\\\"state\\\":\\\"0\\\",\\\"undefined\\\":true}]\" ],\r\n  \"supplierLinkmans\" : [ \"[{\\\"proIndex\\\":0,\\\"defaultFlag\\\":\\\"1\\\",\\",
            "status": 0,
            "errorMsg": null,
            "operTime": "2020-07-13 14:42:45"
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": null,
            "createTime": null,
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "operId": 2365,
            "title": "供应商",
            "businessType": 1,
            "businessTypes": null,
            "method": "com.qcp.web.controller.masterdata.SupplierController.addSave()",
            "operatorType": 1,
            "operName": "15502169523",
            "deptName": "上海益吉",
            "operUrl": "/sqm-admin/masterdata/supplier/add",
            "operIp": "223.166.81.134",
            "operLocation": "XX XX",
            "operParam": "{\r\n  \"supplierNo\" : [ \"延锋汽车\" ],\r\n  \"supplierName\" : [ \"10023\" ],\r\n  \"supplierType\" : [ \"1\" ],\r\n  \"supplierLevel\" : [ \"0\" ],\r\n  \"state\" : [ \"0\" ],\r\n  \"position0\" : [ \"质量总监\" ],\r\n  \"linkmanName0\" : [ \"张燕\" ],\r\n  \"mobile0\" : [ \"13978698938\" ],\r\n  \"email0\" : [ \"xulixia@imonsoft.com\" ],\r\n  \"address0\" : [ \"墨玉路\" ],\r\n  \"position1\" : [ \"质量主管\" ],\r\n  \"linkmanName1\" : [ \"刘帅\" ],\r\n  \"mobile1\" : [ \"13795240575\" ],\r\n  \"email1\" : [ \"xulixia@imonsoft.com\" ],\r\n  \"address1\" : [ \"昌吉路\" ],\r\n  \"certificate0\" : [ \"16949证书\" ],\r\n  \"startDate0\" : [ \"2020-07-01\" ],\r\n  \"endingDate0\" : [ \"2021-07-21\" ],\r\n  \"finishUserName0\" : [ \"徐丽霞\" ],\r\n  \"lateFinishDate0\" : [ \"2020-07-25\" ],\r\n  \"remindUserName0\" : [ \"徐丽霞\" ],\r\n  \"remindDeadline0\" : [ \"30\" ],\r\n  \"supplierQualifications\" : [ \"[{\\\"proIndex\\\":0,\\\"category\\\":\\\"0\\\",\\\"name\\\":\\\"0\\\",\\\"fileType\\\":\\\"0\\\",\\\"certificate\\\":\\\"16949证书\\\",\\\"startDate\\\":\\\"2020-07-01\\\",\\\"endingDate\\\":\\\"2021-07-21\\\",\\\"finishUserId\\\":\\\"2c93b4f16bb1e070016bd5752f110397\\\",\\\"finishUserName\\\":\\\"徐丽霞\\\",\\\"lateFinishDate\\\":\\\"2020-07-25\\\",\\\"remindUserId\\\":\\\"2c93b4f16bb1e070016bd5752f110397\\\",\\\"remindUserName\\\":\\\"徐丽霞\\\",\\\"remindDeadline\\\":\\\"30\\\",\\\"validity\\\":\\\"0\\\",\\\"state\\\":\\\"0\\\",\\\"undefined\\\":true}]\" ],\r\n  \"supplierLinkmans\" : [ \"[{\\\"proIndex\\\":0,\\\"defaultFlag\\\":\\\"1\\\",\\\"defaultFlags\\\":\\\"是\\\",\\\"position\\\":\\\"质量总监\\\",\\\"linkmanName\\\":\\\"张燕\\\",\\\"mobile\\\":\\\"13978698938\\\",\\\"email\\\":\\\"xulixia@imonsoft.com\\\",\\\"address\\\":\\\"墨玉路\\\",\\\"undefined\\\":true},{\\\"proIndex\\\":1,\\\"defaultFlag\\\":\\\"0\\\",\\\"defaultFlags\\\":\\\"否\\\",\\\"position\\\":\\\"质量主管\\\",\\\"linkmanName\\\":\\\"刘帅\\\",\\\"mobile\\\":\\\"13795240575\\\",\\\"email\\\":\\\"xulixia@imonsoft.com\\\",\\\"address\\\":\\\"昌吉路\\\",\\\"undefined\\\":true}]\" ]\r\n}",
            "status": 0,
            "errorMsg": null,
            "operTime": "2020-07-13 14:37:59"
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": null,
            "createTime": null,
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "operId": 2364,
            "title": "供应商业绩评价详细",
            "businessType": 6,
            "businessTypes": null,
            "method": "com.qcp.statistical.controller.PerformanceAppraisalController.export()",
            "operatorType": 1,
            "operName": "15502169523",
            "deptName": "上海益吉",
            "operUrl": "/sqm-admin/statistical/performanceAppraisal/export",
            "operIp": "223.166.81.134",
            "operLocation": "XX XX",
            "operParam": "{\r\n  \"supplierNo\" : [ \"\" ],\r\n  \"supplierName\" : [ \"\" ],\r\n  \"year\" : [ \"\" ],\r\n  \"mouth\" : [ \"\" ]\r\n}",
            "status": 0,
            "errorMsg": null,
            "operTime": "2020-07-13 13:16:55"
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": null,
            "createTime": null,
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "operId": 2363,
            "title": "定时任务",
            "businessType": 2,
            "businessTypes": null,
            "method": "com.qcp.quartz.controller.SysJobController.run()",
            "operatorType": 1,
            "operName": "15502169523",
            "deptName": "上海益吉",
            "operUrl": "/sqm-admin/monitor/job/run",
            "operIp": "223.166.83.113",
            "operLocation": "XX XX",
            "operParam": "{\r\n  \"jobId\" : [ \"1\" ],\r\n  \"jobGroup\" : [ \"DEFAULT\" ]\r\n}",
            "status": 0,
            "errorMsg": null,
            "operTime": "2020-06-05 18:46:12"
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": null,
            "createTime": null,
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "operId": 2362,
            "title": "定时任务",
            "businessType": 2,
            "businessTypes": null,
            "method": "com.qcp.quartz.controller.SysJobController.run()",
            "operatorType": 1,
            "operName": "15502169523",
            "deptName": "上海益吉",
            "operUrl": "/sqm-admin/monitor/job/run",
            "operIp": "223.166.83.113",
            "operLocation": "XX XX",
            "operParam": "{\r\n  \"jobId\" : [ \"1\" ],\r\n  \"jobGroup\" : [ \"DEFAULT\" ]\r\n}",
            "status": 0,
            "errorMsg": null,
            "operTime": "2020-06-05 18:44:54"
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": null,
            "createTime": null,
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "operId": 2361,
            "title": "定时任务",
            "businessType": 2,
            "businessTypes": null,
            "method": "com.qcp.quartz.controller.SysJobController.run()",
            "operatorType": 1,
            "operName": "15502169523",
            "deptName": "上海益吉",
            "operUrl": "/sqm-admin/monitor/job/run",
            "operIp": "116.238.17.81",
            "operLocation": "XX XX",
            "operParam": "{\r\n  \"jobId\" : [ \"1\" ],\r\n  \"jobGroup\" : [ \"DEFAULT\" ]\r\n}",
            "status": 0,
            "errorMsg": null,
            "operTime": "2020-06-04 15:14:30"
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": null,
            "createTime": null,
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "operId": 2360,
            "title": "年度计划",
            "businessType": 10,
            "businessTypes": null,
            "method": "com.qcp.sysman.controller.AuditPlanController.projectApprSave()",
            "operatorType": 1,
            "operName": "15502169523",
            "deptName": "上海益吉",
            "operUrl": "/sqm-admin/sysman/auditPlan/projectApprSave",
            "operIp": "223.166.83.113",
            "operLocation": "XX XX",
            "operParam": "{\r\n  \"approvalState\" : [ \"0\" ],\r\n  \"approvalAdvice\" : [ \"Ok\" ],\r\n  \"dataId\" : [ \"82b9a87ea62f11ea927c00163e1ae183\" ],\r\n  \"dataFlag\" : [ \"auditPlan.projectAppr\" ]\r\n}",
            "status": 0,
            "errorMsg": null,
            "operTime": "2020-06-04 14:51:48"
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": null,
            "createTime": null,
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "operId": 2359,
            "title": "审核计划",
            "businessType": 2,
            "businessTypes": null,
            "method": "com.qcp.sysman.controller.AuditPlanController.editSave()",
            "operatorType": 1,
            "operName": "15502169523",
            "deptName": "上海益吉",
            "operUrl": "/sqm-admin/sysman/auditPlan/edit",
            "operIp": "223.166.83.113",
            "operLocation": "XX XX",
            "operParam": "{\r\n  \"planId\" : [ \"82b9a87ea62f11ea927c00163e1ae183\" ],\r\n  \"supplierId\" : [ \"02c832caf95511e98b0300163e1ae183\" ],\r\n  \"supplier.supplierNo\" : [ \"C1001\" ],\r\n  \"supplier.supplierName\" : [ \"太仓市汇湖电镀有限公司B-1车间\" ],\r\n  \"reviewCategory\" : [ \"0\" ],\r\n  \"quaCategory\" : [ \"0\" ],\r\n  \"quaName\" : [ \"0\" ],\r\n  \"cerValidityStart\" : [ \"2020-06-02\" ],\r\n  \"cerValidityEnd\" : [ \"2020-06-04\" ],\r\n  \"linkmanName\" : [ \"ss\" ],\r\n  \"email\" : [ \"43\" ],\r\n  \"address\" : [ \"ddd\" ],\r\n  \"mainProducts\" : [ \"dgfdg\" ],\r\n  \"reviewWay\" : [ \"0\" ],\r\n  \"projectApprUserId\" : [ \"2c93b4f1676ebbe0016771ef50b6001d\" ],\r\n  \"projectApprUserName\" : [ \"王海森\" ],\r\n  \"resultApprUserId\" : [ \"2c93b4f1676ebbe0016771ef50b6001d\" ],\r\n  \"resultApprUserName\" : [ \"王海森\" ]\r\n}",
            "status": 0,
            "errorMsg": null,
            "operTime": "2020-06-04 14:51:33"
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": null,
            "createTime": null,
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "operId": 2358,
            "title": "审核计划",
            "businessType": 2,
            "businessTypes": null,
            "method": "com.qcp.sysman.controller.AuditPlanController.editSave()",
            "operatorType": 1,
            "operName": "15502169523",
            "deptName": "上海益吉",
            "operUrl": "/sqm-admin/sysman/auditPlan/edit",
            "operIp": "223.166.83.113",
            "operLocation": "XX XX",
            "operParam": "{\r\n  \"planId\" : [ \"82b9a87ea62f11ea927c00163e1ae183\" ],\r\n  \"supplierId\" : [ \"02c832caf95511e98b0300163e1ae183\" ],\r\n  \"supplier.supplierNo\" : [ \"C1001\" ],\r\n  \"supplier.supplierName\" : [ \"太仓市汇湖电镀有限公司B-1车间\" ],\r\n  \"reviewCategory\" : [ \"0\" ],\r\n  \"quaCategory\" : [ \"0\" ],\r\n  \"quaName\" : [ \"0\" ],\r\n  \"cerValidityStart\" : [ \"2020-06-02\" ],\r\n  \"cerValidityEnd\" : [ \"2020-06-04\" ],\r\n  \"linkmanName\" : [ \"ss\" ],\r\n  \"email\" : [ \"43\" ],\r\n  \"address\" : [ \"ddd\" ],\r\n  \"mainProducts\" : [ \"dgfdg\" ],\r\n  \"reviewWay\" : [ \"0\" ],\r\n  \"projectApprUserId\" : [ \"2c93b4f16bb1e070016bd5752f110397\" ],\r\n  \"projectApprUserName\" : [ \"徐丽霞\" ],\r\n  \"resultApprUserId\" : [ \"2c93b4f16bb1e070016bd5752f110397\" ],\r\n  \"resultApprUserName\" : [ \"徐丽霞\" ]\r\n}",
            "status": 0,
            "errorMsg": null,
            "operTime": "2020-06-04 14:50:10"
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": null,
            "createTime": null,
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "operId": 2357,
            "title": "审核计划",
            "businessType": 1,
            "businessTypes": null,
            "method": "com.qcp.sysman.controller.AuditPlanController.addSave()",
            "operatorType": 1,
            "operName": "15502169523",
            "deptName": "上海益吉",
            "operUrl": "/sqm-admin/sysman/auditPlan/add",
            "operIp": "223.166.83.113",
            "operLocation": "XX XX",
            "operParam": "{\r\n  \"planId\" : [ \"\" ],\r\n  \"supplierId\" : [ \"02c832caf95511e98b0300163e1ae183\" ],\r\n  \"supplier.supplierNo\" : [ \"C1001\" ],\r\n  \"supplier.supplierName\" : [ \"太仓市汇湖电镀有限公司B-1车间\" ],\r\n  \"reviewCategory\" : [ \"0\" ],\r\n  \"quaCategory\" : [ \"0\" ],\r\n  \"quaName\" : [ \"0\" ],\r\n  \"cerValidityStart\" : [ \"2020-06-02\" ],\r\n  \"cerValidityEnd\" : [ \"2020-06-04\" ],\r\n  \"linkmanName\" : [ \"ss\" ],\r\n  \"email\" : [ \"43\" ],\r\n  \"address\" : [ \"ddd\" ],\r\n  \"mainProducts\" : [ \"dgfdg\" ],\r\n  \"reviewWay\" : [ \"0\" ],\r\n  \"projectApprUserId\" : [ \"0960c182369111ea8b0300163e1ae183\" ],\r\n  \"projectApprUserName\" : [ \"许文平\" ],\r\n  \"resultApprUserId\" : [ \"0963f3da369111ea8b0300163e1ae183\" ],\r\n  \"resultApprUserName\" : [ \"黄子重\" ]\r\n}",
            "status": 0,
            "errorMsg": null,
            "operTime": "2020-06-04 14:49:18"
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": null,
            "createTime": null,
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "operId": 2356,
            "title": "供应商",
            "businessType": 1,
            "businessTypes": null,
            "method": "com.qcp.web.controller.masterdata.SupplierController.addSave()",
            "operatorType": 1,
            "operName": "13162062572",
            "deptName": "上海益吉(内部)",
            "operUrl": "/sqm-admin/masterdata/supplier/add",
            "operIp": "210.22.121.246",
            "operLocation": "上海 上海",
            "operParam": "{\r\n  \"supplierNo\" : [ \"11-12\" ],\r\n  \"supplierName\" : [ \"测试益吉\" ],\r\n  \"supplierType\" : [ \"0\" ],\r\n  \"supplierLevel\" : [ \"0\" ],\r\n  \"state\" : [ \"0\" ],\r\n  \"position0\" : [ \"销售\" ],\r\n  \"linkmanName0\" : [ \"张销售\" ],\r\n  \"mobile0\" : [ \"13162062572\" ],\r\n  \"email0\" : [ \"zhang@qq.com\" ],\r\n  \"address0\" : [ \"安亭大厦\" ],\r\n  \"certificate0\" : [ \"zzzs-11-12\" ],\r\n  \"startDate0\" : [ \"2019-11-01\" ],\r\n  \"endingDate0\" : [ \"2019-11-30\" ],\r\n  \"finishUserName0\" : [ \"陈丽娟\" ],\r\n  \"lateFinishDate0\" : [ \"2019-11-29\" ],\r\n  \"remindUserName0\" : [ \"杨彪\" ],\r\n  \"remindDeadline0\" : [ \"30\" ],\r\n  \"supplierQualifications\" : [ \"[{\\\"proIndex\\\":0,\\\"category\\\":\\\"0\\\",\\\"name\\\":\\\"0\\\",\\\"fileType\\\":\\\"0\\\",\\\"certificate\\\":\\\"zzzs-11-12\\\",\\\"startDate\\\":\\\"2019-11-01\\\",\\\"endingDate\\\":\\\"2019-11-30\\\",\\\"finishUserId\\\":\\\"2c93b4f16ca4dac8016ca90d62f102a8\\\",\\\"finishUserName\\\":\\\"陈丽娟\\\",\\\"lateFinishDate\\\":\\\"2019-11-29\\\",\\\"remindUserId\\\":\\\"2c93b4f16774ac33016776e5fa72000d\\\",\\\"remindUserName\\\":\\\"杨彪\\\",\\\"remindDeadline\\\":\\\"30\\\",\\\"validity\\\":\\\"0\\\",\\\"state\\\":\\\"0\\\",\\\"undefined\\\":true}]\" ],\r\n  \"supplierLinkmans\" : [ \"[{\\\"proIndex\\\":0,\\\"defaultFlag\\\":\\\"1\\\",\\\"defaultFlags\\\":\\\"是\\\",\\\"position\\\":\\\"销售\\\",\\\"linkmanName\\\":\\\"张销售\\\",\\\"mobile\\\":\\\"13162062572\\\",\\\"email\\\":\\\"zhang@qq.com\\\",\\\"address\\\":\\\"安亭大厦\\\",\\\"undefined\\\":true}]\" ]\r\n}",
            "status": 0,
            "errorMsg": null,
            "operTime": "2019-11-12 18:11:22"
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": null,
            "createTime": null,
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "operId": 2355,
            "title": "定时任务",
            "businessType": 2,
            "businessTypes": null,
            "method": "com.qcp.quartz.controller.SysJobController.run()",
            "operatorType": 1,
            "operName": "admin",
            "deptName": "上海益吉",
            "operUrl": "/sqm-admin/monitor/job/run",
            "operIp": "127.0.0.1",
            "operLocation": "内网IP",
            "operParam": "{\r\n  \"jobId\" : [ \"1\" ],\r\n  \"jobGroup\" : [ \"DEFAULT\" ]\r\n}",
            "status": 0,
            "errorMsg": null,
            "operTime": "2019-10-31 17:16:32"
        }
    ],
    "code": 0
}
exports.jobsList = logsList