const fileTaskManagement = {
  "total": 3,
  "rows": [
      {
          "companyId": "402880e762656861016266cc46140049",
          "companyName": null,
          "searchValue": null,
          "createBy": null,
          "createTime": null,
          "updateBy": null,
          "updateTime": null,
          "createUserName": "admin",
          "updateUserName": "admin",
          "remark": null,
          "deleteFlag": "0",
          "createUserId": "admin",
          "createDate": "2020-07-13 17:13:13",
          "updateUserId": "admin",
          "updateDate": "2020-07-13 17:13:54",
          "params": {},
          "taskId": "12f1f1ccc4e911ea9c0b00163e1ae183",
          "taskNo": "FT-2020070006",
          "supplierId": "02c832caf95511e98b0300163e1ae183",
          "supplier": {
              "companyId": null,
              "companyName": null,
              "searchValue": null,
              "createBy": null,
              "createTime": null,
              "updateBy": null,
              "updateTime": null,
              "createUserName": null,
              "updateUserName": null,
              "remark": null,
              "deleteFlag": null,
              "createUserId": null,
              "createDate": null,
              "updateUserId": null,
              "updateDate": null,
              "params": {},
              "supplierId": "02c832caf95511e98b0300163e1ae183",
              "supplierNo": "C1001",
              "supplierName": "太仓市汇湖电镀有限公司B-1车间",
              "supplierType": null,
              "supplierTargetValue": null,
              "state": null,
              "supplierLinkman": null,
              "supplierQualification": null,
              "supplierFile": null,
              "removeFileTag": null,
              "mobile": null,
              "email": null,
              "address": null,
              "linkmanName": null,
              "supplierLevel": null,
              "windowTag": null
          },
          "fileType": "3",
          "compPeoId": "admin",
          "compPeoName": "admin",
          "approverId": "2c93b4f16bb1e070016bd5752f110397",
          "approverName": "徐丽霞",
          "compStartDate": "2020-07-12",
          "compEndDate": "2020-08-19",
          "compActualDate": "2020-07-13",
          "taskState": "1",
          "apprState": "0",
          "fileState": "0",
          "dayNum": 10
      },
      {
          "companyId": "402880e762656861016266cc46140049",
          "companyName": null,
          "searchValue": null,
          "createBy": null,
          "createTime": null,
          "updateBy": null,
          "updateTime": null,
          "createUserName": "admin",
          "updateUserName": "admin",
          "remark": null,
          "deleteFlag": "0",
          "createUserId": "admin",
          "createDate": "2020-07-13 16:53:58",
          "updateUserId": "admin",
          "updateDate": "2020-07-13 16:58:10",
          "params": {},
          "taskId": "62f25739c4e611ea9c0b00163e1ae183",
          "taskNo": "FT-2020070005",
          "supplierId": "02cd6e9df95511e98b0300163e1ae183",
          "supplier": {
              "companyId": null,
              "companyName": null,
              "searchValue": null,
              "createBy": null,
              "createTime": null,
              "updateBy": null,
              "updateTime": null,
              "createUserName": null,
              "updateUserName": null,
              "remark": null,
              "deleteFlag": null,
              "createUserId": null,
              "createDate": null,
              "updateUserId": null,
              "updateDate": null,
              "params": {},
              "supplierId": "02cd6e9df95511e98b0300163e1ae183",
              "supplierNo": "C1002",
              "supplierName": "上海达克罗涂复工业有限公司",
              "supplierType": null,
              "supplierTargetValue": null,
              "state": null,
              "supplierLinkman": null,
              "supplierQualification": null,
              "supplierFile": null,
              "removeFileTag": null,
              "mobile": null,
              "email": null,
              "address": null,
              "linkmanName": null,
              "supplierLevel": null,
              "windowTag": null
          },
          "fileType": "2",
          "compPeoId": "admin",
          "compPeoName": "admin",
          "approverId": "2c93b4f16bb1e070016bd5752f110397",
          "approverName": "徐丽霞",
          "compStartDate": "2020-07-12",
          "compEndDate": "2020-07-15",
          "compActualDate": "2020-07-13",
          "taskState": "2",
          "apprState": "1",
          "fileState": "0",
          "dayNum": 10
      },
      {
          "companyId": "402880e762656861016266cc46140049",
          "companyName": null,
          "searchValue": null,
          "createBy": null,
          "createTime": null,
          "updateBy": null,
          "updateTime": null,
          "createUserName": "13162062572",
          "updateUserName": "13162062572",
          "remark": null,
          "deleteFlag": "0",
          "createUserId": "2c93b4f16ca4dac8016ca90d62f102a8",
          "createDate": "2019-10-28 19:48:21",
          "updateUserId": "2c93b4f16ca4dac8016ca90d62f102a8",
          "updateDate": "2019-10-28 19:51:01",
          "params": {},
          "taskId": "d6610262f97811e98b0300163e1ae183",
          "taskNo": "FT-2019100004",
          "supplierId": "038820aff95511e98b0300163e1ae183",
          "supplier": {
              "companyId": null,
              "companyName": null,
              "searchValue": null,
              "createBy": null,
              "createTime": null,
              "updateBy": null,
              "updateTime": null,
              "createUserName": null,
              "updateUserName": null,
              "remark": null,
              "deleteFlag": null,
              "createUserId": null,
              "createDate": null,
              "updateUserId": null,
              "updateDate": null,
              "params": {},
              "supplierId": "038820aff95511e98b0300163e1ae183",
              "supplierNo": "C2025",
              "supplierName": "上海艺嘉金属制品有限公司",
              "supplierType": null,
              "supplierTargetValue": null,
              "state": null,
              "supplierLinkman": null,
              "supplierQualification": null,
              "supplierFile": null,
              "removeFileTag": null,
              "mobile": null,
              "email": null,
              "address": null,
              "linkmanName": null,
              "supplierLevel": null,
              "windowTag": null
          },
          "fileType": "1",
          "compPeoId": "2c93b4f16ca4dac8016ca90d62f102a8",
          "compPeoName": "陈丽娟",
          "approverId": "2c93b4f16ca4dac8016ca90d62f102a8",
          "approverName": "陈丽娟",
          "compStartDate": "2019-08-02",
          "compEndDate": "2019-10-31",
          "compActualDate": "2019-10-28",
          "taskState": "2",
          "apprState": "1",
          "fileState": "0",
          "dayNum": 3
      }
  ],
  "code": 0
}
const fileList = {
  "total": 2,
  "rows": [
      {
          "companyId": null,
          "companyName": null,
          "searchValue": null,
          "createBy": null,
          "createTime": null,
          "updateBy": null,
          "updateTime": null,
          "createUserName": null,
          "updateUserName": null,
          "remark": null,
          "deleteFlag": null,
          "createUserId": null,
          "createDate": null,
          "updateUserId": null,
          "updateDate": null,
          "params": {},
          "fileType": "2",
          "compPeoName": "admin",
          "compActualDate": "2020-07-13",
          "fileName": "保证书.docx",
          "filePath": "http://enjoyquality.cn/sqm-admin/profile/upload/2020/07/13/8bd7e314d541315ce372f3ac7b8894b9.docx",
          "dataFlag": "fileTask.finishFile",
          "dataId": "62f25739c4e611ea9c0b00163e1ae183",
          "state": "0",
          "supplierNo": "C1002",
          "supplierName": "上海达克罗涂复工业有限公司"
      },
      {
          "companyId": null,
          "companyName": null,
          "searchValue": null,
          "createBy": null,
          "createTime": null,
          "updateBy": null,
          "updateTime": null,
          "createUserName": null,
          "updateUserName": null,
          "remark": null,
          "deleteFlag": null,
          "createUserId": null,
          "createDate": null,
          "updateUserId": null,
          "updateDate": null,
          "params": {},
          "fileType": "1",
          "compPeoName": "陈丽娟",
          "compActualDate": "2019-10-28",
          "fileName": "SQM 1.0版本_2019-10-23测试版.xlsx",
          "filePath": "http://www.enjoyquality.cn/sqm-admin/profile/upload/2019/10/28/258a144f3b2f86847cd531a9d470b766.xlsx",
          "dataFlag": "fileTask.finishFile",
          "dataId": "d6610262f97811e98b0300163e1ae183",
          "state": "0",
          "supplierNo": "C2025",
          "supplierName": "上海艺嘉金属制品有限公司"
      }
  ],
  "code": 0
}
exports.fileList = fileList
exports.fileTaskManagement = fileTaskManagement
