const complaintFormManagement = {
    "total": 3,
    "rows": [
        {
            "companyId": "402880e762656861016266cc46140049",
            "companyName": null,
            "searchValue": null,
            "createBy": null,
            "createTime": null,
            "updateBy": null,
            "updateTime": null,
            "createUserName": "冯佳俊",
            "updateUserName": null,
            "remark": null,
            "deleteFlag": "0",
            "createUserId": "2c93b4f16931b21f016932b47c670116",
            "createDate": "2019-10-28 19:55:43",
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "invoiceId": "ddf43893f97911e98b0300163e1ae183",
            "invoiceNo": "D-KS-2019100011",
            "partId": "27ea9c22f97011e98b0300163e1ae183",
            "part": {
                "companyId": null,
                "companyName": null,
                "searchValue": null,
                "createBy": null,
                "createTime": null,
                "updateBy": null,
                "updateTime": null,
                "createUserName": null,
                "updateUserName": null,
                "remark": null,
                "deleteFlag": null,
                "createUserId": null,
                "createDate": null,
                "updateUserId": null,
                "updateDate": null,
                "params": {},
                "partId": "27ea9c22f97011e98b0300163e1ae183",
                "partNo": null,
                "partName": "螺母",
                "materials": null,
                "specification": "3mm",
                "image": null,
                "partType": null,
                "state": null,
                "version": null,
                "recordContent": null,
                "approverId": null,
                "approverName": null,
                "partClient": null,
                "partChangeRecordsp": null,
                "partFile": null,
                "removeFileTag": null,
                "clientNo": null,
                "clientName": null,
                "windowTag": null
            },
            "batchNo": "TS-1028-001",
            "supplierId": "038820aff95511e98b0300163e1ae183",
            "supplier": {
                "companyId": null,
                "companyName": null,
                "searchValue": null,
                "createBy": null,
                "createTime": null,
                "updateBy": null,
                "updateTime": null,
                "createUserName": null,
                "updateUserName": null,
                "remark": null,
                "deleteFlag": null,
                "createUserId": null,
                "createDate": null,
                "updateUserId": null,
                "updateDate": null,
                "params": {},
                "supplierId": "038820aff95511e98b0300163e1ae183",
                "supplierNo": "C2025",
                "supplierName": "上海艺嘉金属制品有限公司",
                "supplierType": null,
                "supplierTargetValue": null,
                "state": null,
                "supplierLinkman": null,
                "supplierQualification": null,
                "supplierFile": null,
                "removeFileTag": null,
                "mobile": null,
                "email": null,
                "address": null,
                "linkmanName": null,
                "supplierLevel": null,
                "windowTag": null
            },
            "findTime": "2019-09-19",
            "inspectNum": 10,
            "rejectNum": 3,
            "rejectRatio": 30,
            "createStage": "2",
            "invoiceDate": "2019-09-18 00:00:00",
            "planFinishDate": "2019-09-30 00:00:00",
            "finishDate": null,
            "disqualificationDescription": null,
            "provisionalMeasures": null,
            "primaryCause": null,
            "longtermMeasure": null,
            "implementationEffect": null,
            "agreeClose": null,
            "apprUserId": "2c93b4f167a2e5060167a6b5c10400f6",
            "apprUserName": "欧添",
            "state": "0",
            "puserName": null,
            "pdate": null,
            "euserName": null,
            "edate": null,
            "puserId": null,
            "euserId": null,
            "cuserId": null,
            "cuserName": null,
            "adate": null,
            "luserName": null,
            "cdate": null,
            "auserId": null,
            "ldate": null,
            "luserId": null,
            "auserName": null
        },
        {
            "companyId": "402880e762656861016266cc46140049",
            "companyName": null,
            "searchValue": null,
            "createBy": null,
            "createTime": null,
            "updateBy": null,
            "updateTime": null,
            "createUserName": "13162062572",
            "updateUserName": "13162062572",
            "remark": null,
            "deleteFlag": "0",
            "createUserId": "2c93b4f16ca4dac8016ca90d62f102a8",
            "createDate": "2019-10-28 19:30:39",
            "updateUserId": "2c93b4f16ca4dac8016ca90d62f102a8",
            "updateDate": "2019-10-28 19:32:11",
            "params": {},
            "invoiceId": "5d8751e5f97611e98b0300163e1ae183",
            "invoiceNo": "D-OT-2019100010",
            "partId": "d0be3d97f97011e98b0300163e1ae183",
            "part": {
                "companyId": null,
                "companyName": null,
                "searchValue": null,
                "createBy": null,
                "createTime": null,
                "updateBy": null,
                "updateTime": null,
                "createUserName": null,
                "updateUserName": null,
                "remark": null,
                "deleteFlag": null,
                "createUserId": null,
                "createDate": null,
                "updateUserId": null,
                "updateDate": null,
                "params": {},
                "partId": "d0be3d97f97011e98b0300163e1ae183",
                "partNo": null,
                "partName": "转轴",
                "materials": null,
                "specification": "GG-10*28-01",
                "image": null,
                "partType": null,
                "state": null,
                "version": null,
                "recordContent": null,
                "approverId": null,
                "approverName": null,
                "partClient": null,
                "partChangeRecordsp": null,
                "partFile": null,
                "removeFileTag": null,
                "clientNo": null,
                "clientName": null,
                "windowTag": null
            },
            "batchNo": "P1028-01",
            "supplierId": "038820aff95511e98b0300163e1ae183",
            "supplier": {
                "companyId": null,
                "companyName": null,
                "searchValue": null,
                "createBy": null,
                "createTime": null,
                "updateBy": null,
                "updateTime": null,
                "createUserName": null,
                "updateUserName": null,
                "remark": null,
                "deleteFlag": null,
                "createUserId": null,
                "createDate": null,
                "updateUserId": null,
                "updateDate": null,
                "params": {},
                "supplierId": "038820aff95511e98b0300163e1ae183",
                "supplierNo": "C2025",
                "supplierName": "上海艺嘉金属制品有限公司",
                "supplierType": null,
                "supplierTargetValue": null,
                "state": null,
                "supplierLinkman": null,
                "supplierQualification": null,
                "supplierFile": null,
                "removeFileTag": null,
                "mobile": null,
                "email": null,
                "address": null,
                "linkmanName": null,
                "supplierLevel": null,
                "windowTag": null
            },
            "findTime": "2019-10-01",
            "inspectNum": 20,
            "rejectNum": 20,
            "rejectRatio": 9.52,
            "createStage": "3",
            "invoiceDate": "2019-10-05 00:00:00",
            "planFinishDate": "2019-10-27 00:00:00",
            "finishDate": "2019-10-28 00:00:00",
            "disqualificationDescription": "问题描述挨打苏第三页整后状态安静的感受他的茪规划师的规划局阿萨德刚加上大家好撒的国家嘎嘎信号检测工作现场合作过程中小高层自行车改好现在工厂照相馆更好些分工合作处罚更换新政策法规和幸福感和法规和发过火关系在财富各乡镇采光整后状态安静的感受他的茪规划师的规划局阿萨德刚加上大家好撒的国家嘎嘎信号检测工作现场合作过程中小高层自行车改好现在工厂照相馆更好些分工合作处罚更换新政策法规和幸福感和法规和发过火关",
            "provisionalMeasures": "临时措施安静的感受他的茪规划师的规划局阿萨德刚加上大家好撒的国家嘎嘎信号检测工作现场合作过程中小高层自行车改好现在工厂照相馆更好些分工合作处罚更换新政策法规和幸福感和法规和发过火关系在财富各乡镇采光整后状态安静的感受他的茪规划师的规划局阿萨德刚加上大家好撒的国家嘎嘎信号检测工作现场合作过程中小高层自行车改好现在工厂照相馆更好些分工合作处罚更换新政策法规和幸福感和法规和发过火关系在财富各乡镇采光整后",
            "primaryCause": "根本原因整后状态安静的感受他的茪规划师的规划局阿萨德刚加上大家好撒的国家嘎嘎信号检测工作现场合作过程中小高层自行车改好现在工厂照相馆更好些分工合作处罚更换新政策法规和幸福感和法规和发过火关系在财富各乡镇采光整后状态安静的感受他的茪规划师的规划局阿萨德刚加上大家好撒的国家嘎嘎信号检测工作现场合作过程中小高层自行车改好现在工厂照相馆更好些分工合作处罚更换新政策法规和幸福感和法规和发过火关系在财富各乡镇",
            "longtermMeasure": "长期措施整后状态安静的感受他的茪规划师的规划局阿萨德刚加上大家好撒的国家嘎嘎信号检测工作现场合作过程中小高层自行车改好现在工厂照相馆更好些分工合作处罚更换新政策法规和幸福感和法规和发过火关系在财富各乡镇采光整后状态安静的感受他的茪规划师的规划局阿萨德刚加上大家好撒的国家嘎嘎信号检测工作现场合作过程中小高层自行车改好现在工厂照相馆更好些分工合作处罚更换新政策法规和幸福感和法规和发过火关系在财富各乡镇",
            "implementationEffect": "实施效果",
            "agreeClose": "同一关闭整后状态安静的感受他的茪规划师的规划局阿萨德刚加上大家好撒的国家嘎嘎信号检测工作现场合作过程中小高层自行车改好现在工厂照相馆更好些分工合作处罚更换新政策法规和幸福感和法规和发过火关系在财富各乡镇采光整后状态安静的感受他的茪规划师的规划局阿萨德刚加上大家好撒的国家嘎嘎信号检测工作现场合作过程中小高层自行车改好现在工厂照相馆更好些分工合作处罚更换新政策法规和幸福感和法规和发过火关系在财富各乡镇",
            "apprUserId": "2c93b4f16ca4dac8016ca90d62f102a8",
            "apprUserName": "陈丽娟",
            "state": "2",
            "puserName": "杨彪",
            "pdate": "2019-10-28 00:00:00",
            "euserName": "王海森",
            "edate": "2019-11-29 00:00:00",
            "puserId": "2c93b4f16774ac33016776e5fa72000d",
            "euserId": "2c93b4f1676ebbe0016771ef50b6001d",
            "cuserId": "2c93b4f1676ebbe0016771ef50b6001d",
            "cuserName": "王海森",
            "adate": "2019-12-31 00:00:00",
            "luserName": "杨彪",
            "cdate": "2019-10-28 00:00:00",
            "auserId": "2c93b4f167491df501674e96842800cb",
            "ldate": "2019-10-31 00:00:00",
            "luserId": "2c93b4f16774ac33016776e5fa72000d",
            "auserName": "陈平"
        },
        {
            "companyId": "402880e762656861016266cc46140049",
            "companyName": null,
            "searchValue": null,
            "createBy": null,
            "createTime": null,
            "updateBy": null,
            "updateTime": null,
            "createUserName": "admin",
            "updateUserName": "admin",
            "remark": null,
            "deleteFlag": "0",
            "createUserId": "admin",
            "createDate": "2020-07-13 16:31:49",
            "updateUserId": "admin",
            "updateDate": "2020-07-13 16:33:22",
            "params": {},
            "invoiceId": "4ae62b6ec4e311ea9c0b00163e1ae183",
            "invoiceNo": "D-ZC-2020070012",
            "partId": "9cf23272c4db11ea9c0b00163e1ae183",
            "part": {
                "companyId": null,
                "companyName": null,
                "searchValue": null,
                "createBy": null,
                "createTime": null,
                "updateBy": null,
                "updateTime": null,
                "createUserName": null,
                "updateUserName": null,
                "remark": null,
                "deleteFlag": null,
                "createUserId": null,
                "createDate": null,
                "updateUserId": null,
                "updateDate": null,
                "params": {},
                "partId": "9cf23272c4db11ea9c0b00163e1ae183",
                "partNo": null,
                "partName": "滤清器",
                "materials": null,
                "specification": "210*270",
                "image": null,
                "partType": null,
                "state": null,
                "version": null,
                "recordContent": null,
                "approverId": null,
                "approverName": null,
                "partClient": null,
                "partChangeRecordsp": null,
                "partFile": null,
                "removeFileTag": null,
                "clientNo": null,
                "clientName": null,
                "windowTag": null
            },
            "batchNo": "P20200-0715-1/2",
            "supplierId": "02cd6e9df95511e98b0300163e1ae183",
            "supplier": {
                "companyId": null,
                "companyName": null,
                "searchValue": null,
                "createBy": null,
                "createTime": null,
                "updateBy": null,
                "updateTime": null,
                "createUserName": null,
                "updateUserName": null,
                "remark": null,
                "deleteFlag": null,
                "createUserId": null,
                "createDate": null,
                "updateUserId": null,
                "updateDate": null,
                "params": {},
                "supplierId": "02cd6e9df95511e98b0300163e1ae183",
                "supplierNo": "C1002",
                "supplierName": "上海达克罗涂复工业有限公司",
                "supplierType": null,
                "supplierTargetValue": null,
                "state": null,
                "supplierLinkman": null,
                "supplierQualification": null,
                "supplierFile": null,
                "removeFileTag": null,
                "mobile": null,
                "email": null,
                "address": null,
                "linkmanName": null,
                "supplierLevel": null,
                "windowTag": null
            },
            "findTime": "2020-07-13",
            "inspectNum": 5,
            "rejectNum": 3,
            "rejectRatio": 1,
            "createStage": "1",
            "invoiceDate": "2020-07-13 00:00:00",
            "planFinishDate": "2020-07-15 00:00:00",
            "finishDate": "2020-07-13 00:00:00",
            "disqualificationDescription": "滤清器抽检中长度不合格，超出允许范围",
            "provisionalMeasures": "对应的几台生产仪器已停产，调试员正进行调试",
            "primaryCause": "生产仪器老化",
            "longtermMeasure": "老旧仪器分配相应负责人，每三个小时检查仪器运作情况并记录上报",
            "implementationEffect": "效果不错，大大提高了品控质量。",
            "agreeClose": "同一",
            "apprUserId": "2c93b4f16bb1e070016bd5752f110397",
            "apprUserName": "徐丽霞",
            "state": "2",
            "puserName": "王海森",
            "pdate": "2020-07-13 00:00:00",
            "euserName": "王海森",
            "edate": "2020-07-15 00:00:00",
            "puserId": "2c93b4f1676ebbe0016771ef50b6001d",
            "euserId": "2c93b4f1676ebbe0016771ef50b6001d",
            "cuserId": "2c93b4f1676ebbe0016771ef50b6001d",
            "cuserName": "王海森",
            "adate": "2020-07-15 00:00:00",
            "luserName": "王海森",
            "cdate": "2020-07-13 00:00:00",
            "auserId": "2c93b4f16bb1e070016bd5752f110397",
            "ldate": "2020-07-13 00:00:00",
            "luserId": "2c93b4f1676ebbe0016771ef50b6001d",
            "auserName": "徐丽霞"
        }
    ],
    "code": 0
}
exports.complaintFormManagement = complaintFormManagement