/* eslint-disable */
const logsList = {
    "total": 25,
    "rows": [{
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": "System",
            "createTime": "2020-01-05 19:16:55",
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": "人员性别选项",
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "dictId": "000a7ea48e1747a8b211c3adf5f24863",
            "dictName": "性别",
            "dictType": "系统级",
            "status": 0,
            "dictDetails": [
                { "dictId": "001", "dicName": "男" },
                { "dictId": "002", "dicName": "女" }
            ]
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": "System",
            "createTime": "2020-01-05 19:18:46",
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "dictId": "0018415a28c24894a69dc4a89d16058f",
            "dictName": "供应商分类",
            "dictType": "系统级",
            "status": 0,
            "dictDetails": [
                { "dictId": "001", "dicName": "零件" },
                { "dictId": "002", "dicName": "原材料" }
            ]
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": "System",
            "createTime": "2020-01-05 19:17:28",
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "dictId": "002d1d433c784b30a30c6d7af54ca5c1",
            "dictName": "D",
            "dictType": null,
            "status": 0,
            "dictDetails": []
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": "System",
            "createTime": "2020-01-05 19:19:03",
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "dictId": "006a6effe1df47048f238e55bf6a91d6",
            "dictName": "返工/返修",
            "dictType": null,
            "status": 0
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": "System",
            "createTime": "2020-01-05 19:17:14",
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "dictId": "00caf91a5fa746518334854bb913e991",
            "dictName": "总成",
            "dictType": null,
            "status": 0
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": "System",
            "createTime": "2020-01-05 19:19:29",
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "dictId": "00e4909df24a47bf9ae23e8a19b94b3b",
            "dictName": "每班",
            "dictType": null,
            "status": 0
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": "System",
            "createTime": "2020-01-05 19:17:33",
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "dictId": "00ea029316f74c73a60f1ed2da4d5911",
            "dictName": "储存",
            "dictType": null,
            "status": 0
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": "System",
            "createTime": "2020-01-05 19:17:47",
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "dictId": "00ececd33167468e8f654a6685eed620",
            "dictName": "系统",
            "dictType": null,
            "status": 0
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": "System",
            "createTime": "2020-01-05 19:17:56",
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "dictId": "00f8a23fde454c5c9b096cdf58f1d1a7",
            "dictName": "环",
            "dictType": null,
            "status": 0
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": "System",
            "createTime": "2020-01-05 19:17:46",
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "dictId": "010b14e56b0f443a87e7bb97789c99f3",
            "dictName": "正确的位置",
            "dictType": null,
            "status": 0
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": "System",
            "createTime": "2020-01-05 19:16:48",
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "dictId": "010e7f5f2835482da14bb66ef94afeb8",
            "dictName": "数量正确",
            "dictType": null,
            "status": 0
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": "System",
            "createTime": "2020-01-05 19:18:00",
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "dictId": "01281c4c021e48e0aba328d526e116f5",
            "dictName": "卡尺",
            "dictType": null,
            "status": 0
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": "System",
            "createTime": "2020-01-05 19:19:01",
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "dictId": "013066903c3a4a1d98fb00308daeff27",
            "dictName": "产品/过程 规范/公差",
            "dictType": null,
            "status": 0
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": "System",
            "createTime": "2020-01-05 19:18:32",
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "dictId": "0181754c370c4a118f5d7a90f5f096ce",
            "dictName": "料",
            "dictType": null,
            "status": 0
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": "System",
            "createTime": "2020-01-05 19:18:15",
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "dictId": "0191db4bfc9348ae93f2a0922867468b",
            "dictName": "组件",
            "dictType": null,
            "status": 0
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": "System",
            "createTime": "2020-01-05 19:17:58",
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "dictId": "0193f7a65bef4669b4b3b78efe270bc8",
            "dictName": "系统",
            "dictType": null,
            "status": 0
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": "System",
            "createTime": "2020-01-05 19:19:01",
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "dictId": "01a0fcb9fda44414aa0b8b08efb7eb9b",
            "dictName": "S",
            "dictType": null,
            "status": 0
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": "System",
            "createTime": "2020-01-05 19:18:34",
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "dictId": "01a296bd3c544032b3d17b3b8d809fce",
            "dictName": "零件",
            "dictType": null,
            "status": 0
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": "System",
            "createTime": "2020-01-05 19:16:46",
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "dictId": "01a6699d40f3465e8531593bb33ed0d1",
            "dictName": "0.45-0.55MPA",
            "dictType": null,
            "status": 0
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": "System",
            "createTime": "2020-01-05 19:19:28",
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "dictId": "01d55ac7781c4bc4a5a6b8a4fdcbdb09",
            "dictName": "0.45-0.55MPA",
            "dictType": null,
            "status": 0
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": "System",
            "createTime": "2020-01-05 19:17:02",
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "dictId": "01d8271ab4474470971791e4d8957ef2",
            "dictName": "抽样频次",
            "dictType": null,
            "status": 0
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": "System",
            "createTime": "2020-01-05 19:16:51",
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "dictId": "01f7c5e3e76d49388180031f8a83f86d",
            "dictName": "要素分类",
            "dictType": "222",
            "status": 0
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": "System",
            "createTime": "2020-01-05 19:17:31",
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "dictId": "020c844cf5414284847515d30ffea905",
            "dictName": "每班",
            "dictType": null,
            "status": 0
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": "System",
            "createTime": "2020-01-05 19:19:13",
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "dictId": "021ac1b1bd2a488ea3602512c6201842",
            "dictName": "S",
            "dictType": null,
            "status": 0
        },
        {
            "companyId": null,
            "companyName": null,
            "searchValue": null,
            "createBy": "System",
            "createTime": "2020-01-05 19:17:00",
            "updateBy": null,
            "updateTime": null,
            "createUserName": null,
            "updateUserName": null,
            "remark": null,
            "deleteFlag": null,
            "createUserId": null,
            "createDate": null,
            "updateUserId": null,
            "updateDate": null,
            "params": {},
            "dictId": "021f3c8d24d64f79bbe49449574eb6c8",
            "dictName": "包装标识",
            "dictType": null,
            "status": 0
        }
    ],
    "code": 0
}
exports.jobsList = logsList